"use client";

import Link from "next/link";
import type { ComponentType } from "react";
import {
  Crown,
  Coins,
  Twitch,
  Youtube,
  Instagram,
  MessageCircle,
  Music2,
} from "lucide-react";

import { DiscordIcon, KickIcon } from "@/components/brand-icons";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { cn } from "@/lib/utils";
import { formatCurrency, formatDate, formatNumber } from "@/lib/utils/format";
import { EmptyState } from "@/components/empty-state";
import type {
  CreatorListItem,
  CreatorDealStatus,
  CreatorSocialPlatform,
} from "@/lib/backend-api";

import { CreatorRowActions } from "./creator-row-actions";
import { InfoHint } from "./info-hint";
import type { CreatorSocialSummary } from "../_queries/socials-by-user";

// Plain-English one-liners for each per-creator stat box — shared by the
// card-grid `Stat` cells and the compact list-view column headers so both
// views explain the same number the same way. Surfaced via a small "ⓘ"
// InfoHint next to each label (reuses the repo's shadcn Tooltip pattern).
const STAT_HINTS = {
  code: "The creator's affiliate code — players enter it to be attributed to this creator.",
  wagerVolume:
    "All-time wager volume from players referred by this creator's code (staff excluded). Money players risked = house income (emerald).",
  ggr: "Gross gaming revenue (wager − payout) from this creator's code cohort over the selected window — counted only while the code was active. House POV: emerald = house win, rose = house loss.",
  signups: "Players who signed up using this creator's code (all-time).",
  ftds: "First-time depositors — referred players who deposited at least once. The trailing % is FTDs ÷ signups.",
  capUsed:
    "How much of the deal's withdrawal cap has been converted into payout vouchers — usage of their cash-out cap, NOT money paid out. The sub-line shows how much actually left the platform.",
  dealCost:
    "Worst-case house spend on this creator's active deal over the next 14 days — the deal's total withdrawal cap. Money the house could pay out (rose).",
  leaderboardCost:
    "Worst-case house spend on this creator's affiliate leaderboards over the next 14 days — the house-funded share of those prize pools (rose).",
} as const;

const DEAL_STATUS_STYLE: Record<CreatorDealStatus, string> = {
  scheduled:
    "border-blue-500/30 bg-blue-500/10 text-blue-600 dark:text-blue-400",
  active:
    "border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  completed: "border-muted bg-muted/50 text-muted-foreground",
  terminated:
    "border-rose-500/30 bg-rose-500/10 text-rose-600 dark:text-rose-400",
};

// Platform → icon + brand-ish color. Brand colors are deliberately muted
// (`/15` bg, `/80` text) to fit the admin's neutral palette instead of
// shouting like the real Twitch/YouTube buttons.
const PLATFORM_META: Record<
  CreatorSocialPlatform,
  {
    /** Widened past `LucideIcon` so the brand glyphs (Kick/Discord) fit. */
    icon: ComponentType<{ className?: string; "aria-hidden"?: boolean }>;
    color: string;
    label: string;
  }
> = {
  twitch: {
    icon: Twitch,
    color: "bg-purple-500/15 text-purple-600 dark:text-purple-400",
    label: "Twitch",
  },
  youtube: {
    icon: Youtube,
    color: "bg-rose-500/15 text-rose-600 dark:text-rose-400",
    label: "YouTube",
  },
  kick: {
    icon: KickIcon,
    color: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
    label: "Kick",
  },
  x: {
    icon: MessageCircle,
    color: "bg-zinc-500/15 text-zinc-700 dark:text-zinc-300",
    label: "X",
  },
  instagram: {
    icon: Instagram,
    color: "bg-pink-500/15 text-pink-600 dark:text-pink-400",
    label: "Instagram",
  },
  tiktok: {
    icon: Music2,
    color: "bg-cyan-500/15 text-cyan-600 dark:text-cyan-400",
    label: "TikTok",
  },
  discord: {
    icon: DiscordIcon,
    color: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400",
    label: "Discord",
  },
};

export type CreatorWithSocials = CreatorListItem & {
  socials: CreatorSocialSummary[];
  /** user.affiliate_code — null if the creator doesn't own a code yet. */
  code: string | null;
  /**
   * Wager volume generated by users this creator referred — matches
   * the "Wager Volume" KPI on /creators/[id]. NOT the creator's own
   * personal wagering.
   */
  wagerVolumeUsd: number;
  /** Total signups attributed to this creator (user.referred_by = creator). */
  signups: number;
  /**
   * Lifetime first-time depositors — distinct referred users who have
   * deposited at least once. Same as /creators/[id]'s ftdByPeriod.all.
   */
  ftds: number;
  /**
   * 3-day rolling deposit volume from this creator's affiliates.
   * Surfaced as the "Last 3d" momentum line on the card so the admin
   * can spot who is producing right now.
   */
  deposits3dUsd: number;
  /** 3-day rolling wager volume — same source as deposits3dUsd. */
  wagers3dUsd: number;
  // PnL fields (pnlByPeriod / lifetimePnl) removed from the list-page
  // card — see comment at the (now-removed) PnlStrip call-site. Detail
  // page /creators/[id] still surfaces the proper per-(creator, user)
  // cap'd numbers.
  /**
   * "Converted" — cap-usage (`withdraw_cap_used_usd`) on this
   * creator's active/scheduled deal: how much of stream earnings have
   * been converted into payout vouchers (against the deal's withdraw
   * cap). Note the name is a slight misnomer — this is "converted",
   * NOT necessarily "withdrawn off-platform". The withdraw-vs-still-
   * playing breakdown lives in `withdrawnFromConverted` below.
   * null when the creator has no such deal, or the per-deal fetch
   * failed → the card shows "—".
   */
  convertedUsd: number | null;
  /**
   * Of `convertedUsd` (payout vouchers minted from conversion), how
   * much has actually left the platform via a card_withdrawal_requests
   * row. Split into completed vs in-flight. null when the join failed
   * OR the creator has no withdraw activity tied to conversion
   * vouchers on this deal → the sub-line under Converted is hidden.
   */
  withdrawnFromConverted: {
    withdrawnUsd: number;
    withdrawPendingUsd: number;
  } | null;
  /**
   * 2-week MAX cost projections — worst-case house spend over the
   * next fortnight. `deal2wkMaxUsd` = the active deal's total withdraw
   * cap (`total_withdraw_cap_usd`) — the most the creator can ever
   * withdraw on it. `leaderboard2wkMaxUsd` = the sponsored-weighted
   * prize of every affiliate leaderboard running in the next 14 days.
   * null when the creator has nothing to project → the card hides the
   * row.
   */
  deal2wkMaxUsd: number | null;
  leaderboard2wkMaxUsd: number | null;
  /**
   * Chips beside the creator's name. `withdrawalCapUsd` = the active
   * deal's withdraw cap (`total_withdraw_cap_usd`) — the "max cap for
   * withdrawal". `leaderboardSponsoredPct` = the blended "% we pay"
   * across the creator's leaderboards running in the next 14 days.
   * null when not applicable.
   */
  withdrawalCapUsd: number | null;
  leaderboardSponsoredPct: number | null;
  /**
   * Windowed code-user GGR for this creator's cohort over the selected
   * `?period=` window — the GGR-side (Term 1) of the canonical Net
   * Creator PnL, sourced from `getAllCreatorsNetGgr(period)` and merged
   * on by `creatorUserId`. House-POV: positive = the cohort lost money
   * to us (house win → emerald); negative = we paid the cohort out
   * (house loss → rose). GGR-side ONLY — the full Net PnL (GGR − cost)
   * is a backend round-trip that lives on /creators/[id]. null when the
   * batch GGR fetch failed → the row shows "—".
   */
  windowedGgrUsd: number | null;
  /**
   * True on the "Past Creators" tab — this user was a creator (owned an
   * affiliate code, or has an admin audit role-change → creator) but no
   * longer holds the creator role (deal cancelled, role removed). Drives
   * the subtle "Ex-creator" badge on the row. Same signal + styling the
   * user-detail page's ex-creator badge uses. Defaults to false/absent on
   * the active Fill / Multiplier tabs.
   */
  isPastCreator?: boolean;
};


/**
 * Windowed code-user GGR value, House-POV.
 *   • > 0 → cohort lost money to us → house win → 🟢 emerald, `+` prefix
 *   • < 0 → we paid the cohort out → house loss → 🔴 rose, `−` prefix
 *   • = 0 → no margin → neutral muted "—"
 *   • null → batch fetch failed → muted "—"
 * Mirrors the per-(creator) GGR coloring on /creators/[id]'s PnL panel.
 */
function GgrValue({ usd }: { usd: number | null }) {
  if (usd == null || usd === 0) {
    return <span className="text-muted-foreground/60">—</span>;
  }
  const win = usd > 0;
  return (
    <span
      className={cn(
        "tabular-nums",
        win
          ? "text-emerald-600 dark:text-emerald-400"
          : "text-rose-600 dark:text-rose-400",
      )}
      title={`${usd} USD code-user GGR over the selected window — ${
        win ? "house win (cohort lost to us)" : "house loss (we paid the cohort out)"
      }`}
    >
      {win ? "+" : "−"}
      {formatCurrency(Math.abs(usd))}
    </span>
  );
}

/**
 * Card-grid for /creators replacing the old wide-table layout. Each
 * creator gets a self-contained card with their identity, current deal
 * progress (if any), live indicator, social handles, and the row-action
 * menu — no horizontal scrolling, no truncated columns.
 *
 * Grid: 1 / 2 / 3 cols depending on viewport so cards stay readable
 * (~340px floor) at every width.
 */
export function CreatorCardGrid({
  creators,
}: {
  creators: CreatorWithSocials[];
}) {
  if (creators.length === 0) {
    return (
      <div className="rounded-xl border bg-muted/20">
        <EmptyState
          icon={Crown}
          title="No creators found"
          description="No creators match the current search or tab. Try a different search term or switch the deal program."
        />
      </div>
    );
  }
  return (
    <div className="grid gap-3 grid-cols-1 sm:gap-4 md:grid-cols-2 xl:grid-cols-3">
      {creators.map((creator) => (
        <CreatorCard key={creator.id} creator={creator} />
      ))}
    </div>
  );
}

function CreatorCard({ creator }: { creator: CreatorWithSocials }) {
  const display =
    creator.username ?? creator.email ?? creator.id.slice(0, 8);
  const live = creator.active_session_id !== null;
  const deal = creator.current_deal;
  // "Active" = has a deal in the active state. Distinct from "Live"
  // (currently streaming via `active_session_id`). A creator can be
  // Active (deal in progress this week) without being Live (not on
  // stream right now), so both indicators can co-exist. Scheduled
  // deals NOT counted here — they're not active yet.
  const hasActiveDeal = deal?.status === "active";
  const initials = display.slice(0, 2).toUpperCase();

  return (
    <div className="relative overflow-hidden rounded-2xl border border-border/60 bg-card p-5 transition-all hover:border-border hover:shadow-sm sm:p-6">
      <div className="relative space-y-5">
        {/* IDENTITY */}
        <div className="flex items-start gap-3">
          <Link
            href={`/creators/${creator.id}`}
            className="shrink-0"
            aria-label={`Open ${display}`}
          >
            <Avatar className="size-12 ring-2 ring-background">
              {creator.image && <AvatarImage src={creator.image} alt="" />}
              <AvatarFallback className="text-sm font-semibold">
                {initials}
              </AvatarFallback>
            </Avatar>
          </Link>
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <Link
                href={`/creators/${creator.id}`}
                className="truncate text-base font-semibold leading-tight hover:underline"
              >
                {display}
              </Link>
              {/* "Ex-creator" / canceled indicator — purple outline,
                  same styling + copy as the user-detail page's
                  ex-creator badge. Shown only on the Past Creators tab.
                  Marks a user who was a creator but whose role was
                  removed (deal cancelled / retired). */}
              {creator.isPastCreator && (
                <Badge
                  variant="outline"
                  className="h-5 border-purple-500/40 bg-purple-500/10 py-0 text-[10px] font-medium text-purple-600 dark:text-purple-400"
                  title="Previously had the creator role — creator role since removed (deal cancelled / retired)"
                >
                  Ex-creator
                </Badge>
              )}
              {/* "Active" deal indicator — steady emerald dot. Renders
                  whenever the creator has a deal currently in the
                  active state (this week's deal is running). Visually
                  distinct from the pulsing "Live" badge below so
                  both can show side-by-side on a creator who has a
                  live deal AND is mid-stream. */}
              {hasActiveDeal && (
                <span
                  className="inline-flex items-center gap-1 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-1.5 py-0.5 text-[10px] font-medium text-emerald-600 dark:text-emerald-400"
                  title="Deal is currently active this week"
                >
                  <span className="relative inline-flex size-1.5 rounded-full bg-emerald-500" />
                  Active
                </span>
              )}
              {/* "Live" streaming indicator — pulsing emerald dot.
                  Fires when the creator has an open session (kick
                  stream / deal-day session started). Separate signal
                  from "Active deal" — a creator can have an active
                  deal without being live, and vice versa. */}
              {live && (
                <span className="inline-flex items-center gap-1 text-[11px] font-medium text-emerald-600 dark:text-emerald-400">
                  <span className="relative flex size-1.5">
                    <span className="absolute inline-flex size-full motion-safe:animate-ping rounded-full bg-emerald-500 opacity-75" />
                    <span className="relative inline-flex size-1.5 rounded-full bg-emerald-500" />
                  </span>
                  Live
                </span>
              )}
              {/* Withdrawal cap — the max the creator can pull against
                  their active deal. Rose: house cost exposure. */}
              {creator.withdrawalCapUsd != null && (
                <span
                  className="inline-flex items-center gap-0.5 rounded-full border border-rose-500/30 bg-rose-500/10 px-1.5 py-0.5 text-[10px] font-medium text-rose-600 dark:text-rose-400"
                  title="Max withdrawal cap on the creator's active deal"
                >
                  Cap {formatCurrency(creator.withdrawalCapUsd)}
                </span>
              )}
              {/* Leaderboard — the blended % the house sponsors of this
                  creator's leaderboards running in the next 14 days,
                  plus our dollar cost. */}
              {creator.leaderboardSponsoredPct != null && (
                <span
                  className="inline-flex items-center gap-0.5 rounded-full border border-rose-500/30 bg-rose-500/10 px-1.5 py-0.5 text-[10px] font-medium text-rose-600 dark:text-rose-400"
                  title="Leaderboard: the % we sponsor + our 14-day leaderboard cost"
                >
                  LB {Math.round(creator.leaderboardSponsoredPct)}%
                  {creator.leaderboard2wkMaxUsd != null && (
                    <span className="text-rose-600/70 dark:text-rose-400/70">
                      {" · "}
                      {formatCurrency(creator.leaderboard2wkMaxUsd)}
                    </span>
                  )}
                </span>
              )}
            </div>
            <p className="mt-0.5 truncate text-[11px] text-muted-foreground">
              {formatDate(new Date(creator.created_at))}
              {" · "}
              {formatNumber(creator.total_deals_count)} deals
            </p>
          </div>
          <div className="-mr-1 -mt-1 shrink-0">
            <CreatorRowActions
              userId={creator.id}
              hasActiveSession={live}
              hasActiveDeal={
                deal?.status === "active" || deal?.status === "scheduled"
              }
            />
          </div>
        </div>

        {/* DEAL — borderless, just type + a clean progress bar */}
        <DealSummary deal={deal} />

        {/* 2-WEEK MAX COST — worst-case house spend over the next
            fortnight from this creator's deal + affiliate leaderboards. */}
        <TwoWeekCostRow
          dealUsd={creator.deal2wkMaxUsd}
          leaderboardUsd={creator.leaderboard2wkMaxUsd}
        />

        {/* STATS — single 6-up row, divider-separated, no inner borders */}
        <StatsStrip
          code={creator.code}
          wagerVolumeUsd={creator.wagerVolumeUsd}
          windowedGgrUsd={creator.windowedGgrUsd}
          signups={creator.signups}
          ftds={creator.ftds}
          convertedUsd={creator.convertedUsd}
          withdrawnFromConverted={creator.withdrawnFromConverted}
        />

        {/* MOMENTUM — last 3 days. Reads as a thin support line under
            the lifetime stats so admins can spot who's producing right
            now without digging into the detail page. Hidden when both
            numbers are 0 to keep dormant creators visually quieter. */}
        <MomentumRow
          deposits3dUsd={creator.deposits3dUsd}
          wagers3dUsd={creator.wagers3dUsd}
        />

        {/* PnL strip removed: the proper per-(creator, user) cap that
            keeps a single non-code-depositing user from dragging a
            creator's number into the red lives on /creators/[id]. The
            per-card numbers without that cap were misleading. */}

        {/* SOCIALS */}
        <SocialsRow socials={creator.socials} />
      </div>
    </div>
  );
}

/**
 * Compact list view for /creators — one creator per row, dense and
 * scannable for working through a large roster fast. Surfaces the SAME
 * data the card shows, laid out inline as columns instead of a card:
 * avatar + username (link to the detail page), Active / Live status,
 * current-deal status + fill progress, the affiliate stats (code,
 * wager volume, signups, FTDs, converted), the house-cost chips
 * (withdrawal cap, leaderboard %), and the row-action kebab.
 *
 * House-POV colors preserved exactly as on the card: wager volume +
 * converted-withdrawn (house income / throughput) stay emerald;
 * withdrawal cap + leaderboard cost (house spend) stay rose.
 *
 * Wide screens get a fixed column grid; below `lg` the row degrades to
 * a stacked card-ish block so it stays readable on narrow viewports —
 * no horizontal scrolling.
 */
export function CreatorListView({
  creators,
}: {
  creators: CreatorWithSocials[];
}) {
  if (creators.length === 0) {
    return (
      <div className="rounded-xl border bg-muted/20">
        <EmptyState
          icon={Crown}
          title="No creators found"
          description="No creators match the current search or tab. Try a different search term or switch the deal program."
        />
      </div>
    );
  }
  return (
    <div className="overflow-hidden rounded-xl border border-border/60 bg-card">
      {/* Column header — desktop only. Mirrors the row grid below so the
          inline columns read as a table. Hidden on narrow viewports
          where rows stack. */}
      <div className="hidden border-b border-border/60 bg-muted/30 px-4 py-2.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground lg:grid lg:grid-cols-[minmax(0,2fr)_minmax(0,1.5fr)_minmax(0,0.8fr)_minmax(0,1fr)_minmax(0,1fr)_minmax(0,0.7fr)_minmax(0,0.7fr)_minmax(0,1fr)_2.25rem] lg:items-center lg:gap-3">
        <span>Creator</span>
        <span>Deal</span>
        <span className="flex items-center gap-1">
          Code
          <InfoHint text={STAT_HINTS.code} iconClassName="size-2.5" />
        </span>
        <span className="flex items-center justify-end gap-1">
          Wager Volume
          <InfoHint text={STAT_HINTS.wagerVolume} iconClassName="size-2.5" />
        </span>
        <span className="flex items-center justify-end gap-1">
          GGR
          <InfoHint text={STAT_HINTS.ggr} iconClassName="size-2.5" />
        </span>
        <span className="flex items-center justify-end gap-1">
          Signups
          <InfoHint text={STAT_HINTS.signups} iconClassName="size-2.5" />
        </span>
        <span className="flex items-center justify-end gap-1">
          FTDs
          <InfoHint text={STAT_HINTS.ftds} iconClassName="size-2.5" />
        </span>
        <span className="flex items-center justify-end gap-1">
          Cap used
          <InfoHint text={STAT_HINTS.capUsed} iconClassName="size-2.5" />
        </span>
        <span className="sr-only">Actions</span>
      </div>
      <div className="divide-y divide-border/60">
        {creators.map((creator) => (
          <CreatorListRow key={creator.id} creator={creator} />
        ))}
      </div>
    </div>
  );
}

function CreatorListRow({ creator }: { creator: CreatorWithSocials }) {
  const display =
    creator.username ?? creator.email ?? creator.id.slice(0, 8);
  const live = creator.active_session_id !== null;
  const deal = creator.current_deal;
  const hasActiveDeal = deal?.status === "active";
  const initials = display.slice(0, 2).toUpperCase();
  const conv =
    creator.signups > 0
      ? Math.min(100, (creator.ftds / creator.signups) * 100).toFixed(0)
      : null;

  return (
    <div className="grid grid-cols-1 gap-2 px-4 py-3 transition-colors hover:bg-muted/30 lg:grid-cols-[minmax(0,2fr)_minmax(0,1.5fr)_minmax(0,0.8fr)_minmax(0,1fr)_minmax(0,1fr)_minmax(0,0.7fr)_minmax(0,0.7fr)_minmax(0,1fr)_2.25rem] lg:items-center lg:gap-3">
      {/* IDENTITY — avatar + username link + status badges + house-cost
          chips (cap / leaderboard). Same signals as the card header. */}
      <div className="flex min-w-0 items-center gap-2.5">
        <Link
          href={`/creators/${creator.id}`}
          className="shrink-0"
          aria-label={`Open ${display}`}
        >
          <Avatar className="size-8">
            {creator.image && <AvatarImage src={creator.image} alt="" />}
            <AvatarFallback className="text-[11px] font-semibold">
              {initials}
            </AvatarFallback>
          </Avatar>
        </Link>
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-1.5">
            <Link
              href={`/creators/${creator.id}`}
              className="truncate text-sm font-semibold leading-tight hover:underline"
            >
              {display}
            </Link>
            {/* Ex-creator / canceled indicator — same purple badge + copy
                as the card view + the user-detail page. Past Creators tab
                only. */}
            {creator.isPastCreator && (
              <Badge
                variant="outline"
                className="h-5 border-purple-500/40 bg-purple-500/10 py-0 text-[10px] font-medium text-purple-600 dark:text-purple-400"
                title="Previously had the creator role — creator role since removed (deal cancelled / retired)"
              >
                Ex-creator
              </Badge>
            )}
            {hasActiveDeal && (
              <span
                className="inline-flex items-center gap-1 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-1.5 py-0.5 text-[10px] font-medium text-emerald-600 dark:text-emerald-400"
                title="Deal is currently active this week"
              >
                <span className="relative inline-flex size-1.5 rounded-full bg-emerald-500" />
                Active
              </span>
            )}
            {live && (
              <span className="inline-flex items-center gap-1 text-[10px] font-medium text-emerald-600 dark:text-emerald-400">
                <span className="relative flex size-1.5">
                  <span className="absolute inline-flex size-full motion-safe:animate-ping rounded-full bg-emerald-500 opacity-75" />
                  <span className="relative inline-flex size-1.5 rounded-full bg-emerald-500" />
                </span>
                Live
              </span>
            )}
            {creator.withdrawalCapUsd != null && (
              <span
                className="inline-flex items-center gap-0.5 rounded-full border border-rose-500/30 bg-rose-500/10 px-1.5 py-0.5 text-[10px] font-medium text-rose-600 dark:text-rose-400"
                title="Max withdrawal cap on the creator's active deal"
              >
                Cap {formatCurrency(creator.withdrawalCapUsd)}
              </span>
            )}
            {creator.leaderboardSponsoredPct != null && (
              <span
                className="inline-flex items-center gap-0.5 rounded-full border border-rose-500/30 bg-rose-500/10 px-1.5 py-0.5 text-[10px] font-medium text-rose-600 dark:text-rose-400"
                title="Leaderboard: the % we sponsor + our 14-day leaderboard cost"
              >
                LB {Math.round(creator.leaderboardSponsoredPct)}%
                {creator.leaderboard2wkMaxUsd != null && (
                  <span className="text-rose-600/70 dark:text-rose-400/70">
                    {" · "}
                    {formatCurrency(creator.leaderboard2wkMaxUsd)}
                  </span>
                )}
              </span>
            )}
          </div>
          <p className="mt-0.5 truncate text-[11px] text-muted-foreground">
            {formatDate(new Date(creator.created_at))}
            {" · "}
            {formatNumber(creator.total_deals_count)} deals
          </p>
        </div>
      </div>

      {/* DEAL — compact status pill + fill progress. Mirrors the card's
          DealSummary, condensed to a single line + thin bar. */}
      <ListDealCell deal={deal} />

      {/* CODE */}
      <ListStatCell label="Code">
        {creator.code ? (
          <span
            className="block truncate font-mono text-sm font-semibold"
            title={creator.code}
          >
            {creator.code}
          </span>
        ) : (
          <span className="block text-sm text-muted-foreground/60">—</span>
        )}
      </ListStatCell>

      {/* WAGER VOLUME — emerald (house income), same as the card. */}
      <ListStatCell label="Wager Volume" align="right">
        <span
          className="block truncate text-sm font-semibold tabular-nums text-emerald-600 dark:text-emerald-400"
          title={`${creator.wagerVolumeUsd} USD — wagers from referred users`}
        >
          {creator.wagerVolumeUsd > 0
            ? formatCurrency(creator.wagerVolumeUsd)
            : "—"}
        </span>
      </ListStatCell>

      {/* GGR — windowed code-user GGR, House-POV (emerald = house win,
          rose = house loss). Same color rule as the card. */}
      <ListStatCell label="GGR" align="right">
        <span className="block truncate text-sm font-semibold">
          <GgrValue usd={creator.windowedGgrUsd} />
        </span>
      </ListStatCell>

      {/* SIGNUPS */}
      <ListStatCell label="Signups" align="right">
        <span className="block truncate text-sm font-semibold tabular-nums">
          {creator.signups > 0 ? formatNumber(creator.signups) : "—"}
        </span>
      </ListStatCell>

      {/* FTDs — with conversion % trailing, matching the card. */}
      <ListStatCell label="FTDs" align="right">
        <span className="flex items-baseline justify-start gap-1 lg:justify-end">
          <span className="text-sm font-semibold tabular-nums">
            {creator.ftds > 0 ? formatNumber(creator.ftds) : "—"}
          </span>
          {conv !== null && (
            <span className="font-mono text-[10px] text-muted-foreground/70">
              {conv}%
            </span>
          )}
        </span>
      </ListStatCell>

      {/* CAP USED — deal-cap usage (neutral), relabeled from the old
          "Converted" misnomer (the field is cap-usage, not money out),
          with the withdrawn sub-line in emerald when there's off-
          platform activity, same split as the card. */}
      <ListStatCell label="Cap used" align="right">
        <span
          className="block truncate text-sm font-semibold tabular-nums"
          title={
            creator.convertedUsd != null
              ? `${creator.convertedUsd} USD of the deal's withdraw cap used (minted into payout vouchers)`
              : "No active deal"
          }
        >
          {creator.convertedUsd != null
            ? formatCurrency(creator.convertedUsd)
            : "—"}
        </span>
        {creator.convertedUsd != null &&
          creator.withdrawnFromConverted != null &&
          (creator.withdrawnFromConverted.withdrawnUsd > 0 ||
            creator.withdrawnFromConverted.withdrawPendingUsd > 0) && (
            <span className="mt-0.5 block truncate font-mono text-[10px] text-emerald-600/80 dark:text-emerald-400/80">
              ↳ {formatCurrency(creator.withdrawnFromConverted.withdrawnUsd)}{" "}
              withdrawn
              {creator.withdrawnFromConverted.withdrawPendingUsd > 0 && (
                <>
                  {" "}
                  · +
                  {formatCurrency(
                    creator.withdrawnFromConverted.withdrawPendingUsd,
                  )}{" "}
                  in flight
                </>
              )}
            </span>
          )}
      </ListStatCell>

      {/* ACTIONS — same kebab as the card. */}
      <div className="flex justify-end lg:justify-center">
        <CreatorRowActions
          userId={creator.id}
          hasActiveSession={live}
          hasActiveDeal={
            deal?.status === "active" || deal?.status === "scheduled"
          }
        />
      </div>
    </div>
  );
}

// A list-row stat cell. Renders an inline uppercase label only below
// `lg` (where the row stacks and the column header is hidden); at `lg`+
// the header row provides the labels so the cell shows just the value.
function ListStatCell({
  label,
  align = "left",
  children,
}: {
  label: string;
  align?: "left" | "right";
  children: React.ReactNode;
}) {
  return (
    <div
      className={cn(
        "flex items-center justify-between gap-2 lg:block",
        align === "right" && "lg:text-right",
      )}
    >
      <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground lg:hidden">
        {label}
      </span>
      <div className="min-w-0">{children}</div>
    </div>
  );
}

// Compact deal cell for the list row — status pill + used/cap on one
// line, a thin progress bar below. Mirrors the card's DealSummary in a
// denser footprint. "No deal" collapses to a single muted line.
function ListDealCell({
  deal,
}: {
  deal: CreatorListItem["current_deal"];
}) {
  if (!deal) {
    return (
      <div className="flex items-center justify-between gap-2 lg:block">
        <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground lg:hidden">
          Deal
        </span>
        <span className="flex items-center gap-1.5 text-[11px] text-muted-foreground/70">
          <Coins className="size-3" />
          No active deal
        </span>
      </div>
    );
  }

  const fillsPct =
    deal.fills_allowed > 0
      ? Math.min(100, (deal.fills_used / deal.fills_allowed) * 100)
      : 0;
  const perFill = parseFloat(deal.per_fill_amount_usd) || 0;
  const totalCap = perFill * deal.fills_allowed;
  const totalUsed = perFill * deal.fills_used;

  return (
    <div className="min-w-0 space-y-1">
      <div className="flex flex-wrap items-center gap-1.5">
        <Badge
          variant="outline"
          className={cn(
            "h-4 px-1.5 text-[10px] font-medium",
            DEAL_STATUS_STYLE[deal.status],
          )}
        >
          {deal.status}
        </Badge>
        <span className="font-mono text-[11px] font-medium tabular-nums">
          <span className="text-foreground">${totalUsed.toFixed(0)}</span>
          <span className="text-muted-foreground">
            {" / $"}
            {totalCap.toFixed(0)}
          </span>
        </span>
        <span className="font-mono text-[10px] text-muted-foreground">
          {deal.fills_used}/{deal.fills_allowed}
        </span>
      </div>
      <div className="h-1 overflow-hidden rounded-full bg-muted">
        <div
          className="h-full rounded-full bg-pink-500 transition-all duration-500"
          style={{ width: `${fillsPct}%` }}
        />
      </div>
    </div>
  );
}

// Single 5-up stats strip replacing the old 2x2-bordered-tile layout.
// Borderless — just type + spacing + subtle vertical hairlines on
// desktop. Cleaner, more scannable, and reads as a single row of
// information rather than separate boxes.
function StatsStrip({
  code,
  wagerVolumeUsd,
  windowedGgrUsd,
  signups,
  ftds,
  convertedUsd,
  withdrawnFromConverted,
}: {
  code: string | null;
  wagerVolumeUsd: number;
  windowedGgrUsd: number | null;
  signups: number;
  ftds: number;
  convertedUsd: number | null;
  withdrawnFromConverted: {
    withdrawnUsd: number;
    withdrawPendingUsd: number;
  } | null;
}) {
  const conv =
    signups > 0 ? Math.min(100, (ftds / signups) * 100).toFixed(0) : null;
  return (
    <div className="grid grid-cols-2 gap-x-3 gap-y-3 sm:grid-cols-6 sm:divide-x sm:divide-border/60">
      <Stat label="Code" hint={STAT_HINTS.code}>
        {code ? (
          <span
            className="block truncate font-mono text-sm font-semibold"
            title={code}
          >
            {code}
          </span>
        ) : (
          <span className="block text-sm text-muted-foreground/60">—</span>
        )}
      </Stat>
      <Stat label="Wager Volume" hint={STAT_HINTS.wagerVolume}>
        <span
          className="block truncate text-sm font-semibold tabular-nums text-emerald-600 dark:text-emerald-400"
          title={`${wagerVolumeUsd} USD — wagers from referred users`}
        >
          {wagerVolumeUsd > 0 ? formatCurrency(wagerVolumeUsd) : "—"}
        </span>
      </Stat>
      {/* Code-User GGR — windowed canonical gaming margin for this
          creator's cohort (House-POV: emerald = house win, rose =
          house loss). GGR-side only; full Net PnL on /creators/[id]. */}
      <Stat label="GGR" hint={STAT_HINTS.ggr}>
        <span className="block truncate text-sm font-semibold">
          <GgrValue usd={windowedGgrUsd} />
        </span>
      </Stat>
      <Stat label="Signups" hint={STAT_HINTS.signups}>
        <span className="block truncate text-sm font-semibold tabular-nums">
          {signups > 0 ? formatNumber(signups) : "—"}
        </span>
      </Stat>
      <Stat
        label="FTDs"
        hint={STAT_HINTS.ftds}
        trailing={
          conv !== null ? (
            <span className="font-mono normal-case text-[10px] text-muted-foreground/70">
              {conv}%
            </span>
          ) : null
        }
      >
        <span className="block truncate text-sm font-semibold tabular-nums">
          {ftds > 0 ? formatNumber(ftds) : "—"}
        </span>
      </Stat>
      {/* Cap used — how much of the deal's withdraw cap has been used
          up (`withdraw_cap_used_usd`). Relabeled from the old
          "Converted" misnomer: the underlying field is cap-USAGE, not
          money actually withdrawn off-platform. Neutral color: it's a
          deal-throughput figure, not a house gain/loss direction.

          Sub-line shows of that cap usage, how much actually left the
          platform (completed card_withdrawal_requests) and how much is
          in flight (pending/processing/shipped). Hidden when there's no
          withdraw activity for this deal so dormant creators stay
          visually quiet. */}
      <Stat label="Cap used" hint={STAT_HINTS.capUsed}>
        <span
          className="block truncate text-sm font-semibold tabular-nums"
          title={
            convertedUsd != null
              ? `${convertedUsd} USD of the deal's withdraw cap used (minted into payout vouchers)`
              : "No active deal"
          }
        >
          {convertedUsd != null ? formatCurrency(convertedUsd) : "—"}
        </span>
        {convertedUsd != null &&
          withdrawnFromConverted != null &&
          (withdrawnFromConverted.withdrawnUsd > 0 ||
            withdrawnFromConverted.withdrawPendingUsd > 0) && (
            <span
              className="mt-0.5 block truncate font-mono text-[10px] text-muted-foreground/80"
              title={
                `${withdrawnFromConverted.withdrawnUsd} USD withdrawn off-platform` +
                (withdrawnFromConverted.withdrawPendingUsd > 0
                  ? ` · ${withdrawnFromConverted.withdrawPendingUsd} USD in flight (pending/processing/shipped)`
                  : "")
              }
            >
              ↳ {formatCurrency(withdrawnFromConverted.withdrawnUsd)} withdrawn
              {withdrawnFromConverted.withdrawPendingUsd > 0 && (
                <>
                  {" "}
                  · +{formatCurrency(withdrawnFromConverted.withdrawPendingUsd)}{" "}
                  in flight
                </>
              )}
            </span>
          )}
      </Stat>
    </div>
  );
}

function Stat({
  label,
  children,
  trailing,
  hint,
}: {
  label: string;
  children: React.ReactNode;
  trailing?: React.ReactNode;
  /** Optional one-line explanation, surfaced as a muted "ⓘ" tooltip. */
  hint?: string;
}) {
  return (
    <div className="min-w-0 sm:px-3 sm:first:pl-0 sm:last:pr-0">
      <div className="flex items-center justify-between gap-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
        <span className="flex items-center gap-1">
          {label}
          {hint && <InfoHint text={hint} iconClassName="size-2.5" />}
        </span>
        {trailing}
      </div>
      <div className="mt-0.5">{children}</div>
    </div>
  );
}

// Deal summary — borderless, type-driven. Status pill + week range on
// the left, total used / cap on the right; thin progress bar full-
// width below. The "no deal" state is just a one-line muted note —
// no need for a dashed-border placeholder taking up real estate.
function DealSummary({
  deal,
}: {
  deal: CreatorListItem["current_deal"];
}) {
  if (!deal) {
    return (
      <p className="flex items-center gap-2 text-[11px] text-muted-foreground/70">
        <Coins className="size-3" />
        No active deal
      </p>
    );
  }

  const fillsPct =
    deal.fills_allowed > 0
      ? Math.min(100, (deal.fills_used / deal.fills_allowed) * 100)
      : 0;
  const perFill = parseFloat(deal.per_fill_amount_usd) || 0;
  const totalCap = perFill * deal.fills_allowed;
  const totalUsed = perFill * deal.fills_used;

  return (
    <div className="space-y-2">
      <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
        <Badge
          variant="outline"
          className={cn(
            "h-5 px-1.5 text-[10px] font-medium",
            DEAL_STATUS_STYLE[deal.status],
          )}
        >
          {deal.status}
        </Badge>
        <span className="text-[11px] text-muted-foreground">
          {formatDate(new Date(deal.week_start_utc))} →{" "}
          {formatDate(new Date(deal.week_end_utc))}
        </span>
        <span className="ml-auto text-xs font-mono font-medium tabular-nums">
          <span className="text-foreground">${totalUsed.toFixed(0)}</span>
          <span className="text-muted-foreground">
            {" / $"}
            {totalCap.toFixed(0)}
          </span>
        </span>
      </div>
      <div className="h-1 overflow-hidden rounded-full bg-muted">
        <div
          className="h-full rounded-full bg-pink-500 transition-all duration-500"
          style={{ width: `${fillsPct}%` }}
        />
      </div>
      <p className="text-[10px] text-muted-foreground">
        <span className="font-mono">
          {deal.fills_used}/{deal.fills_allowed}
        </span>{" "}
        fills · ${perFill.toFixed(0)} each · {fillsPct.toFixed(0)}% used
      </p>
    </div>
  );
}

function SocialsRow({ socials }: { socials: CreatorSocialSummary[] }) {
  if (socials.length === 0) {
    return (
      <p className="text-[11px] italic text-muted-foreground">
        No verified socials yet
      </p>
    );
  }
  return (
    <div className="flex flex-wrap gap-1.5">
      {socials.map((s) => {
        const meta = PLATFORM_META[s.platform];
        const Icon = meta.icon;
        const label = `${meta.label} · @${s.username}`;
        const inner = (
          <>
            <Icon className="size-3" />
            <span className="truncate max-w-[120px]">{s.username}</span>
          </>
        );
        return s.url ? (
          <a
            key={s.id}
            href={s.url}
            target="_blank"
            rel="noreferrer"
            title={label}
            className={cn(
              "inline-flex items-center gap-1 rounded-md px-2 py-0.5 text-[11px] font-medium transition-opacity hover:opacity-80",
              meta.color,
            )}
          >
            {inner}
          </a>
        ) : (
          <span
            key={s.id}
            title={label}
            className={cn(
              "inline-flex items-center gap-1 rounded-md px-2 py-0.5 text-[11px] font-medium",
              meta.color,
            )}
          >
            {inner}
          </span>
        );
      })}
    </div>
  );
}

// 3-day rolling momentum line — deposits + wagers from this creator's
// affiliates over the last 72h. Both staff-excluded at the query level
// (admin / support filtered out), so dollar amounts here match the
// per-creator KPI tiles on /creators/[id].
//
// Both zero → render a single muted "No activity in last 3 days" so the
// row stays quiet for dormant creators. Money values render emerald per
// CLAUDE.md house-POV (deposits + wagers are house income).
function MomentumRow({
  deposits3dUsd,
  wagers3dUsd,
}: {
  deposits3dUsd: number;
  wagers3dUsd: number;
}) {
  const hasActivity = deposits3dUsd > 0 || wagers3dUsd > 0;
  if (!hasActivity) {
    return (
      <p className="text-[10px] italic text-muted-foreground/70">
        No activity in last 3 days
      </p>
    );
  }
  return (
    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px]">
      <span className="flex items-center gap-1 font-semibold uppercase tracking-wider text-muted-foreground">
        Last 3d
        <InfoHint
          text="Deposits + wagers from this creator's referred players over the last 72 hours — a quick momentum read on who's producing right now."
          iconClassName="size-2.5"
        />
      </span>
      <span className="text-muted-foreground">
        Deposits{" "}
        <span className="font-semibold tabular-nums text-emerald-600 dark:text-emerald-400">
          {deposits3dUsd > 0 ? formatCurrency(deposits3dUsd) : "—"}
        </span>
      </span>
      <span className="text-muted-foreground">
        Wagers{" "}
        <span className="font-semibold tabular-nums text-emerald-600 dark:text-emerald-400">
          {wagers3dUsd > 0 ? formatCurrency(wagers3dUsd) : "—"}
        </span>
      </span>
    </div>
  );
}

// 2-week max-cost row — worst-case house spend over the next fortnight.
//   Deal        = the active deal's total withdraw cap — the most the
//                 creator can ever withdraw on it.
//   Leaderboard = sponsored-weighted prize of affiliate leaderboards
//                 whose run window overlaps the next 14d.
// Both are money the house pays out → rose (house loss) per CLAUDE.md.
// Hidden when the creator has neither so dormant cards stay quiet.
function TwoWeekCostRow({
  dealUsd,
  leaderboardUsd,
}: {
  dealUsd: number | null;
  leaderboardUsd: number | null;
}) {
  const hasAny = (dealUsd ?? 0) > 0 || (leaderboardUsd ?? 0) > 0;
  if (!hasAny) return null;
  return (
    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px]">
      <span className="flex items-center gap-1 font-semibold uppercase tracking-wider text-muted-foreground">
        2-Week Max Cost
        <InfoHint
          text="Worst-case house spend on this creator over the next 14 days — the deal's full withdrawal cap plus the house-funded share of their upcoming leaderboard prizes. A ceiling, not money already paid (rose)."
          iconClassName="size-2.5"
        />
      </span>
      <span className="flex items-center gap-1 text-muted-foreground">
        Deal{" "}
        <span className="font-semibold tabular-nums text-rose-600 dark:text-rose-400">
          {dealUsd != null && dealUsd > 0 ? formatCurrency(dealUsd) : "—"}
        </span>
        <InfoHint text={STAT_HINTS.dealCost} iconClassName="size-2.5" />
      </span>
      <span className="flex items-center gap-1 text-muted-foreground">
        Leaderboard{" "}
        <span className="font-semibold tabular-nums text-rose-600 dark:text-rose-400">
          {leaderboardUsd != null && leaderboardUsd > 0
            ? formatCurrency(leaderboardUsd)
            : "—"}
        </span>
        <InfoHint
          text={STAT_HINTS.leaderboardCost}
          iconClassName="size-2.5"
        />
      </span>
    </div>
  );
}

// Re-export Crown for the old fallback if anyone imports from this file
export { Crown };
