"use client";

import Link from "next/link";
import {
  Crown,
  Coins,
  Twitch,
  Youtube,
  Instagram,
  MessageCircle,
  Music2,
  type LucideIcon,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { cn } from "@/lib/utils";
import { formatCurrency, formatDate, formatNumber } from "@/lib/utils/format";
import type {
  CreatorListItem,
  CreatorDealStatus,
  CreatorSocialPlatform,
} from "@/lib/backend-api";

import { CreatorRowActions } from "./creator-row-actions";
import type { CreatorSocialSummary } from "../_queries/socials-by-user";

const DEAL_STATUS_STYLE: Record<CreatorDealStatus, string> = {
  scheduled:
    "border-blue-500/30 bg-blue-500/10 text-blue-600 dark:text-blue-400",
  active:
    "border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  completed: "border-muted bg-muted/50 text-muted-foreground",
  terminated:
    "border-rose-500/30 bg-rose-500/10 text-rose-600 dark:text-rose-400",
};

// Platform → icon + brand-ish color. Brand colors are deliberately muted
// (`/15` bg, `/80` text) to fit the admin's neutral palette instead of
// shouting like the real Twitch/YouTube buttons.
const PLATFORM_META: Record<
  CreatorSocialPlatform,
  { icon: LucideIcon; color: string; label: string }
> = {
  twitch: {
    icon: Twitch,
    color: "bg-purple-500/15 text-purple-600 dark:text-purple-400",
    label: "Twitch",
  },
  youtube: {
    icon: Youtube,
    color: "bg-rose-500/15 text-rose-600 dark:text-rose-400",
    label: "YouTube",
  },
  kick: {
    // lucide doesn't have a Kick icon; reuse Twitch shape, different color
    icon: Twitch,
    color: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
    label: "Kick",
  },
  x: {
    icon: MessageCircle,
    color: "bg-zinc-500/15 text-zinc-700 dark:text-zinc-300",
    label: "X",
  },
  instagram: {
    icon: Instagram,
    color: "bg-pink-500/15 text-pink-600 dark:text-pink-400",
    label: "Instagram",
  },
  tiktok: {
    icon: Music2,
    color: "bg-cyan-500/15 text-cyan-600 dark:text-cyan-400",
    label: "TikTok",
  },
  discord: {
    icon: MessageCircle,
    color: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400",
    label: "Discord",
  },
};

export type CreatorWithSocials = CreatorListItem & {
  socials: CreatorSocialSummary[];
  /** user.affiliate_code — null if the creator doesn't own a code yet. */
  code: string | null;
  /**
   * Wager volume generated by users this creator referred — matches
   * the "Wager Volume" KPI on /creators/[id]. NOT the creator's own
   * personal wagering.
   */
  wagerVolumeUsd: number;
  /** Total signups attributed to this creator (user.referred_by = creator). */
  signups: number;
  /**
   * Lifetime first-time depositors — distinct referred users who have
   * deposited at least once. Same as /creators/[id]'s ftdByPeriod.all.
   */
  ftds: number;
  /**
   * 3-day rolling deposit volume from this creator's affiliates.
   * Surfaced as the "Last 3d" momentum line on the card so the admin
   * can spot who is producing right now.
   */
  deposits3dUsd: number;
  /** 3-day rolling wager volume — same source as deposits3dUsd. */
  wagers3dUsd: number;
  /**
   * Per-period House P&L from this creator's referrals — same
   * canonical balance-sheet formula as the dashboard's Lifetime PnL,
   * evaluated as a DELTA over each window. Trimmed to 1d (the only
   * window the strip displays). 3d also kept since the MomentumRow
   * on the same card reads from it.
   *
   * Referred-user pool excludes admin / support / creator roles AND
   * the creator's own user_id (so other streamers' on-site activity
   * doesn't skew the per-creator number). House POV: positive = we
   * made money, negative = we lost money. null when batch query
   * failed.
   */
  pnlByPeriod: {
    "1d": CreatorPnlPeriodCell;
    "3d": CreatorPnlPeriodCell;
  } | null;
  /**
   * All-time House P&L from this creator's referrals. Snapshot:
   *   pnl = totalDeposits − totalWithdrawals
   *       − currentBalance − currentInventory − currentVouchers
   * Drives the "Lifetime" tile on the per-card PnL strip. Null only
   * when the batched lifetime query failed (best-effort).
   *
   * `totalWagered` mirrors the same field on
   * `lib/queries/creators-types.ts:CreatorLifetimePnl` but is
   * always 0 on the list-page path — the per-card UI doesn't render
   * it (wagerVolumeUsd from affiliate_accounts is shown separately).
   * Field is kept for type-shape parity with the detail page.
   */
  lifetimePnl: {
    totalDeposits: number;
    totalWithdrawals: number;
    totalWagered: number;
    currentBalance: number;
    currentInventory: number;
    currentVouchers: number;
    pnl: number;
  } | null;
};

type CreatorPnlPeriodCell = {
  deposits: number;
  withdrawals: number;
  balanceChange: number;
  inventoryChange: number;
  voucherChange: number;
  pnl: number;
};

/**
 * Card-grid for /creators replacing the old wide-table layout. Each
 * creator gets a self-contained card with their identity, current deal
 * progress (if any), live indicator, social handles, and the row-action
 * menu — no horizontal scrolling, no truncated columns.
 *
 * Grid: 1 / 2 / 3 cols depending on viewport so cards stay readable
 * (~340px floor) at every width.
 */
export function CreatorCardGrid({
  creators,
}: {
  creators: CreatorWithSocials[];
}) {
  if (creators.length === 0) {
    return (
      <div className="flex h-32 items-center justify-center rounded-xl border bg-muted/20 text-sm text-muted-foreground">
        No creators found.
      </div>
    );
  }
  return (
    <div className="grid gap-3 grid-cols-1 sm:gap-4 md:grid-cols-2 xl:grid-cols-3">
      {creators.map((creator) => (
        <CreatorCard key={creator.id} creator={creator} />
      ))}
    </div>
  );
}

function CreatorCard({ creator }: { creator: CreatorWithSocials }) {
  const display =
    creator.username ?? creator.email ?? creator.id.slice(0, 8);
  const live = creator.active_session_id !== null;
  const deal = creator.current_deal;
  const initials = display.slice(0, 2).toUpperCase();

  return (
    <div className="group relative overflow-hidden rounded-2xl border border-border/60 bg-card p-5 transition-all hover:-translate-y-px hover:border-border hover:shadow-lg sm:p-6">
      {/* Subtle pink glow — only visible on hover for a quieter
          default look. */}
      <div
        aria-hidden
        className="pointer-events-none absolute -right-16 -top-16 size-40 rounded-full bg-pink-500/0 blur-3xl transition-colors duration-500 group-hover:bg-pink-500/[0.08]"
      />

      <div className="relative space-y-5">
        {/* IDENTITY */}
        <div className="flex items-start gap-3">
          <Link
            href={`/creators/${creator.id}`}
            className="shrink-0"
            aria-label={`Open ${display}`}
          >
            <Avatar className="size-12 ring-2 ring-background">
              {creator.image && <AvatarImage src={creator.image} alt="" />}
              <AvatarFallback className="bg-pink-500/15 text-sm font-semibold text-pink-700 dark:text-pink-300">
                {initials}
              </AvatarFallback>
            </Avatar>
          </Link>
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <Link
                href={`/creators/${creator.id}`}
                className="truncate text-base font-semibold leading-tight hover:underline"
              >
                {display}
              </Link>
              {live && (
                <span className="inline-flex items-center gap-1 text-[11px] font-medium text-emerald-600 dark:text-emerald-400">
                  <span className="relative flex size-1.5">
                    <span className="absolute inline-flex size-full animate-ping rounded-full bg-emerald-500 opacity-75" />
                    <span className="relative inline-flex size-1.5 rounded-full bg-emerald-500" />
                  </span>
                  Live
                </span>
              )}
            </div>
            <p className="mt-0.5 truncate text-[11px] text-muted-foreground">
              {formatDate(new Date(creator.created_at))}
              {" · "}
              {formatNumber(creator.total_deals_count)} deals
            </p>
          </div>
          <div className="-mr-1 -mt-1 shrink-0">
            <CreatorRowActions
              userId={creator.id}
              hasActiveSession={live}
              hasActiveDeal={
                deal?.status === "active" || deal?.status === "scheduled"
              }
            />
          </div>
        </div>

        {/* DEAL — borderless, just type + a clean progress bar */}
        <DealSummary deal={deal} />

        {/* STATS — single 4-up row, divider-separated, no inner borders */}
        <StatsStrip
          code={creator.code}
          wagerVolumeUsd={creator.wagerVolumeUsd}
          signups={creator.signups}
          ftds={creator.ftds}
        />

        {/* MOMENTUM — last 3 days. Reads as a thin support line under
            the lifetime stats so admins can spot who's producing right
            now without digging into the detail page. Hidden when both
            numbers are 0 to keep dormant creators visually quieter. */}
        <MomentumRow
          deposits3dUsd={creator.deposits3dUsd}
          wagers3dUsd={creator.wagers3dUsd}
        />

        {/* PNL STRIP — 1d window + lifetime snapshot from this
            creator's referrals. Same canonical balance-sheet formula
            as the dashboard's lifetime PnL — evaluated as a delta
            (1d) and a snapshot (Lifetime). House POV: positive =
            we made money (emerald), negative = we lost money (rose).
            Hidden when both queries failed so the card doesn't
            render dashes for everyone. */}
        {(creator.pnlByPeriod || creator.lifetimePnl) && (
          <PnlStrip
            pnlByPeriod={creator.pnlByPeriod}
            lifetimePnl={creator.lifetimePnl}
          />
        )}

        {/* SOCIALS */}
        <SocialsRow socials={creator.socials} />
      </div>
    </div>
  );
}

// Single 4-up stats strip replacing the old 2x2-bordered-tile layout.
// Borderless — just type + spacing + subtle vertical hairlines on
// desktop. Cleaner, more scannable, and reads as a single row of
// information rather than four separate boxes.
function StatsStrip({
  code,
  wagerVolumeUsd,
  signups,
  ftds,
}: {
  code: string | null;
  wagerVolumeUsd: number;
  signups: number;
  ftds: number;
}) {
  const conv =
    signups > 0 ? Math.min(100, (ftds / signups) * 100).toFixed(0) : null;
  return (
    <div className="grid grid-cols-2 gap-x-3 gap-y-3 sm:grid-cols-4 sm:divide-x sm:divide-border/60">
      <Stat label="Code">
        {code ? (
          <span
            className="block truncate font-mono text-sm font-semibold"
            title={code}
          >
            {code}
          </span>
        ) : (
          <span className="block text-sm text-muted-foreground/60">—</span>
        )}
      </Stat>
      <Stat label="Wager Volume">
        <span
          className="block truncate text-sm font-semibold tabular-nums text-emerald-600 dark:text-emerald-400"
          title={`${wagerVolumeUsd} USD — wagers from referred users`}
        >
          {wagerVolumeUsd > 0 ? formatCurrency(wagerVolumeUsd) : "—"}
        </span>
      </Stat>
      <Stat label="Signups">
        <span className="block truncate text-sm font-semibold tabular-nums">
          {signups > 0 ? formatNumber(signups) : "—"}
        </span>
      </Stat>
      <Stat
        label="FTDs"
        trailing={
          conv !== null ? (
            <span className="font-mono normal-case text-[10px] text-muted-foreground/70">
              {conv}%
            </span>
          ) : null
        }
      >
        <span className="block truncate text-sm font-semibold tabular-nums">
          {ftds > 0 ? formatNumber(ftds) : "—"}
        </span>
      </Stat>
    </div>
  );
}

function Stat({
  label,
  children,
  trailing,
}: {
  label: string;
  children: React.ReactNode;
  trailing?: React.ReactNode;
}) {
  return (
    <div className="min-w-0 sm:px-3 sm:first:pl-0 sm:last:pr-0">
      <div className="flex items-center justify-between gap-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
        <span>{label}</span>
        {trailing}
      </div>
      <div className="mt-0.5">{children}</div>
    </div>
  );
}

// Deal summary — borderless, type-driven. Status pill + week range on
// the left, total used / cap on the right; thin progress bar full-
// width below. The "no deal" state is just a one-line muted note —
// no need for a dashed-border placeholder taking up real estate.
function DealSummary({
  deal,
}: {
  deal: CreatorListItem["current_deal"];
}) {
  if (!deal) {
    return (
      <p className="flex items-center gap-2 text-[11px] text-muted-foreground/70">
        <Coins className="size-3" />
        No active deal
      </p>
    );
  }

  const fillsPct =
    deal.fills_allowed > 0
      ? Math.min(100, (deal.fills_used / deal.fills_allowed) * 100)
      : 0;
  const perFill = parseFloat(deal.per_fill_amount_usd) || 0;
  const totalCap = perFill * deal.fills_allowed;
  const totalUsed = perFill * deal.fills_used;

  return (
    <div className="space-y-2">
      <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
        <Badge
          variant="outline"
          className={cn(
            "h-5 px-1.5 text-[10px] font-medium",
            DEAL_STATUS_STYLE[deal.status],
          )}
        >
          {deal.status}
        </Badge>
        <span className="text-[11px] text-muted-foreground">
          {formatDate(new Date(deal.week_start_utc))} →{" "}
          {formatDate(new Date(deal.week_end_utc))}
        </span>
        <span className="ml-auto text-xs font-mono font-medium tabular-nums">
          <span className="text-foreground">${totalUsed.toFixed(0)}</span>
          <span className="text-muted-foreground">
            {" / $"}
            {totalCap.toFixed(0)}
          </span>
        </span>
      </div>
      <div className="h-1 overflow-hidden rounded-full bg-muted">
        <div
          className="h-full rounded-full bg-pink-500 transition-all duration-500"
          style={{ width: `${fillsPct}%` }}
        />
      </div>
      <p className="text-[10px] text-muted-foreground">
        <span className="font-mono">
          {deal.fills_used}/{deal.fills_allowed}
        </span>{" "}
        fills · ${perFill.toFixed(0)} each · {fillsPct.toFixed(0)}% used
      </p>
    </div>
  );
}

function SocialsRow({ socials }: { socials: CreatorSocialSummary[] }) {
  if (socials.length === 0) {
    return (
      <p className="text-[11px] italic text-muted-foreground">
        No verified socials yet
      </p>
    );
  }
  return (
    <div className="flex flex-wrap gap-1.5">
      {socials.map((s) => {
        const meta = PLATFORM_META[s.platform];
        const Icon = meta.icon;
        const label = `${meta.label} · @${s.username}`;
        const inner = (
          <>
            <Icon className="size-3" />
            <span className="truncate max-w-[120px]">{s.username}</span>
          </>
        );
        return s.url ? (
          <a
            key={s.id}
            href={s.url}
            target="_blank"
            rel="noreferrer"
            title={label}
            className={cn(
              "inline-flex items-center gap-1 rounded-md px-2 py-0.5 text-[11px] font-medium transition-opacity hover:opacity-80",
              meta.color,
            )}
          >
            {inner}
          </a>
        ) : (
          <span
            key={s.id}
            title={label}
            className={cn(
              "inline-flex items-center gap-1 rounded-md px-2 py-0.5 text-[11px] font-medium",
              meta.color,
            )}
          >
            {inner}
          </span>
        );
      })}
    </div>
  );
}

// 3-day rolling momentum line — deposits + wagers from this creator's
// affiliates over the last 72h. Both staff-excluded at the query level
// (admin / support filtered out), so dollar amounts here match the
// per-creator KPI tiles on /creators/[id].
//
// Both zero → render a single muted "No activity in last 3 days" so the
// row stays quiet for dormant creators. Money values render emerald per
// CLAUDE.md house-POV (deposits + wagers are house income).
function MomentumRow({
  deposits3dUsd,
  wagers3dUsd,
}: {
  deposits3dUsd: number;
  wagers3dUsd: number;
}) {
  const hasActivity = deposits3dUsd > 0 || wagers3dUsd > 0;
  if (!hasActivity) {
    return (
      <p className="text-[10px] italic text-muted-foreground/70">
        No activity in last 3 days
      </p>
    );
  }
  return (
    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px]">
      <span className="font-semibold uppercase tracking-wider text-muted-foreground">
        Last 3d
      </span>
      <span className="text-muted-foreground">
        Deposits{" "}
        <span className="font-semibold tabular-nums text-emerald-600 dark:text-emerald-400">
          {deposits3dUsd > 0 ? formatCurrency(deposits3dUsd) : "—"}
        </span>
      </span>
      <span className="text-muted-foreground">
        Wagers{" "}
        <span className="font-semibold tabular-nums text-emerald-600 dark:text-emerald-400">
          {wagers3dUsd > 0 ? formatCurrency(wagers3dUsd) : "—"}
        </span>
      </span>
    </div>
  );
}

// Per-period PnL strip — 5 mini-cells (1d / 3d / 7d / 14d / 30d),
// each showing the House P&L from this creator's referrals in that
// window. House POV: positive emerald, negative rose, zero muted "—".
//
// PnL formula (same as the dashboard's Lifetime PnL, evaluated as
// deltas over the window):
//
//   pnl = deposits − withdrawals − balanceChange − inventoryChange − voucherChange
//
// Referred-user pool excludes admin / support / creator role accounts
// and the creator's own user_id, so other streamers' on-site activity
// doesn't skew the number.
//
// Compact layout: 2-up grid (1d + Lifetime), divider-separated, label
// above value. Lifetime takes the visual weight (admins asked for
// "easy to read" — and the all-time number is the natural anchor).
// 1d sits next to it to call out recent activity.
function PnlStrip({
  pnlByPeriod,
  lifetimePnl,
}: {
  pnlByPeriod: NonNullable<CreatorWithSocials["pnlByPeriod"]> | null;
  lifetimePnl: NonNullable<CreatorWithSocials["lifetimePnl"]> | null;
}) {
  // 1d cell — falls back to a flat-zero placeholder when the windowed
  // query failed (per the existing best-effort pattern). Same for
  // lifetime.
  const d1 = pnlByPeriod?.["1d"] ?? null;
  const life = lifetimePnl;

  function color(v: number): string {
    if (v > 0) return "text-emerald-600 dark:text-emerald-400";
    if (v < 0) return "text-rose-600 dark:text-rose-400";
    return "text-muted-foreground/60";
  }

  const d1Tooltip = d1
    ? `1d: deposits ${formatCurrency(d1.deposits)} ` +
      `− withdrawals ${formatCurrency(d1.withdrawals)} ` +
      `− balance Δ ${formatCurrency(d1.balanceChange)} ` +
      `− inventory Δ ${formatCurrency(d1.inventoryChange)} ` +
      `− voucher Δ ${formatCurrency(d1.voucherChange)}`
    : undefined;

  const lifeTooltip = life
    ? `Lifetime: deposits ${formatCurrency(life.totalDeposits)} ` +
      `− withdrawals ${formatCurrency(life.totalWithdrawals)} ` +
      `− current balance ${formatCurrency(life.currentBalance)} ` +
      `− current inventory ${formatCurrency(life.currentInventory)} ` +
      `− current vouchers ${formatCurrency(life.currentVouchers)}`
    : undefined;

  return (
    <div>
      <div className="mb-1 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
        <span>PnL</span>
        <span
          className="text-muted-foreground/60 normal-case"
          title="Same balance-sheet formula as the dashboard's Lifetime PnL. 1d is the windowed delta, Lifetime is the all-time snapshot. Positive = we made money."
        >
          (house POV)
        </span>
      </div>
      <div className="grid grid-cols-2 divide-x divide-border/60">
        <div className="min-w-0 pr-3" title={d1Tooltip}>
          <div className="text-[10px] uppercase tracking-wider text-muted-foreground/70">
            1d
          </div>
          <div
            className={cn(
              "truncate text-xs font-semibold tabular-nums",
              color(d1?.pnl ?? 0),
            )}
          >
            {!d1 || d1.pnl === 0 ? "—" : formatCurrency(d1.pnl)}
          </div>
        </div>
        <div className="min-w-0 pl-3" title={lifeTooltip}>
          <div className="text-[10px] uppercase tracking-wider text-muted-foreground/70">
            Lifetime
          </div>
          <div
            className={cn(
              "truncate text-sm font-bold tabular-nums",
              color(life?.pnl ?? 0),
            )}
          >
            {!life || life.pnl === 0 ? "—" : formatCurrency(life.pnl)}
          </div>
        </div>
      </div>
    </div>
  );
}

// Re-export Crown for the old fallback if anyone imports from this file
export { Crown };
