import { getDb } from "@/lib/db";
import { getExcludedUserIds } from "@/lib/excluded-users/fetch";
import { blacklistNotInClause } from "./_blacklist";
import {
  WAGER_TYPES_SQL,
  GAMING_PAYOUT_TYPES_SQL,
} from "@/lib/metrics/ledger-sets";

/**
 * Cohort retention analysis.
 *
 * Users are grouped by signup bucket (week or month). For each bucket we
 * compute the per-period retention: the % of users in that cohort that
 * still placed a wager (pack_opening / battle_bet / battle_sponsorship)
 * in weeks/months N after signup. Revenue retention is the canonical GGR
 * generated by the cohort in that same period.
 *
 * GGR uses the CANONICAL definition from `@/lib/metrics` (the same one the
 * /analytics headline, dashboard, /ggr, money-flow and cost-breakdown use):
 *
 *   cohort GGR = Σ|wager| − ( Σ inventory.value_at_obtained[pack|battle]
 *                             + Σ|battle_refund| )
 *
 * Card conversions (card_sale / reward_card_sale / card_exchange) are
 * NEUTRAL and are NOT on the payout side — the dominant pack/battle payout
 * is the inventory delta, not a ledger type. This replaces the old local
 * 4-type payout list (which wrongly subtracted card_sale / reward_card_sale
 * and a non-existent ledger upgrader_payout), so cohort revenue now
 * reconciles with the canonical GGR everywhere else.
 *
 * Staff (admin / support) AND creators are excluded — they skew every
 * cohort and are not real customers (matches the canonical real-customer
 * scope).
 *
 * Buckets are truncated to the start of the week (Monday) or month. We cap
 * the cohort count so a small-to-medium-sized DB doesn't explode into
 * thousands of rows; cohorts older than the cap fall off the top.
 */

export type CohortGranularity = "week" | "month";

export type CohortRow = {
  cohort: string; // ISO date of bucket start
  label: string; // pretty label for axis ("Feb 5" / "Jan 2024")
  size: number; // count of users in cohort
  // 10 columns: period 0 through period 9+
  retained: number[];
  revenue: number[];
};

export type CohortData = {
  granularity: CohortGranularity;
  maxPeriods: number;
  rows: CohortRow[];
};

// Wager + ledger gaming-payout type sets come from the canonical
// `@/lib/metrics/ledger-sets` — WAGER_TYPES_SQL =
// ('pack_opening','battle_bet','battle_sponsorship'); GAMING_PAYOUT_TYPES_SQL
// = ('battle_refund'). No local list (the old broken 4-type payout list,
// which subtracted card_sale / reward_card_sale and a non-existent ledger
// upgrader_payout, is gone). The dominant pack/battle payout is the
// inventory delta (see the `payout_inventory` CTE), NOT a ledger type.

const MAX_COHORTS = 16;
const MAX_PERIODS = 10;

export async function getCohortRetention(
  granularity: CohortGranularity,
): Promise<CohortData> {
  const db = await getDb();
  const dateTrunc = granularity === "week" ? "week" : "month";
  const periodInterval = granularity === "week" ? "7 days" : "1 month";
  const cohortHorizon = granularity === "week" ? "140 days" : "36 months";
  const excluded = await getExcludedUserIds();
  const blacklistIdNotIn = blacklistNotInClause("u.id", excluded);

  // Pull cohorts + activity in a single pass. `period_index` is integer
  // distance between activity bucket and signup bucket; clamp to the last
  // bucket so "9+" collapses long-tail activity.
  // Period-index expression reused for ledger (created_at) and inventory
  // (obtained_at) activity — integer bucket distance from the cohort's
  // signup bucket, clamped so "9+" collapses long-tail activity.
  const periodIndexExpr = (tsCol: string) => `LEAST(
    ${MAX_PERIODS - 1},
    FLOOR(EXTRACT(EPOCH FROM (date_trunc('${dateTrunc}', ${tsCol}) - c.cohort))
      / EXTRACT(EPOCH FROM INTERVAL '${periodInterval}'))::int
  )`;

  const rows = await db.$queryRawUnsafe<
    {
      cohort: Date;
      size: string;
      period_index: number | null;
      retained: string | null;
      revenue: string | null;
    }[]
  >(`
    WITH cohorts AS (
      SELECT
        date_trunc('${dateTrunc}', u.created_at)::date AS cohort,
        u.id AS user_id,
        u.created_at
      FROM "user" u
      WHERE u.role NOT IN ('admin', 'support', 'creator') ${blacklistIdNotIn}
        AND u.created_at >= NOW() - INTERVAL '${cohortHorizon}'
    ),
    cohort_sizes AS (
      SELECT cohort, COUNT(*)::text AS size
      FROM cohorts
      GROUP BY cohort
    ),
    -- Non-borrow battle sessions: battles with zero borrow_percentage.
    -- Used on BOTH the wager and inventory-payout sides so borrow plays
    -- drop out symmetrically (canonical GGR excludes borrow entirely).
    non_borrow_battle_sessions AS (
      SELECT bp.game_session_id
      FROM battle_participants bp
      JOIN battles b ON b.id = bp.battle_id
      WHERE COALESCE(b.borrow_percentage, 0) = 0
    ),
    -- Wager activity: canonical WAGER_TYPES, borrow plays excluded.
    activity AS (
      SELECT
        c.cohort,
        ${periodIndexExpr("lt.created_at")} AS period_index,
        c.user_id,
        lt.amount
      FROM cohorts c
      JOIN ledger_transactions lt ON lt.user_id = c.user_id
      WHERE lt.status = 'completed'
        AND lt.type IN ${WAGER_TYPES_SQL}
        AND lt.created_at >= c.created_at
        AND (
          (lt.type = 'pack_opening' AND (lt.description IS NULL OR lt.description NOT ILIKE '%borrow%'))
          OR (lt.type IN ('battle_bet','battle_sponsorship') AND lt.game_session_id IN (SELECT game_session_id FROM non_borrow_battle_sessions))
        )
    ),
    -- Ledger gaming-payout leg: battle_refund cash winner only (the only
    -- ledger-resident gaming payout). card_sale / reward_card_sale are
    -- NEUTRAL and intentionally NOT here.
    payout_ledger AS (
      SELECT
        c.cohort,
        ${periodIndexExpr("lt.created_at")} AS period_index,
        lt.amount
      FROM cohorts c
      JOIN ledger_transactions lt ON lt.user_id = c.user_id
      WHERE lt.status = 'completed'
        AND lt.type IN ${GAMING_PAYOUT_TYPES_SQL}
        AND lt.created_at >= c.created_at
    ),
    -- Dominant pack/battle payout: the inventory delta (value of cards the
    -- user kept), bucketed by obtained_at. Borrow plays excluded to match
    -- the wager side. source_id is the game_session_id for pack/battle rows.
    payout_inventory AS (
      SELECT
        c.cohort,
        ${periodIndexExpr("ui.obtained_at")} AS period_index,
        ui.value_at_obtained AS amount
      FROM cohorts c
      JOIN user_inventory ui ON ui.user_id = c.user_id
      WHERE ui.source_type IN ('pack','battle')
        AND ui.obtained_at >= c.created_at
        AND (
          (ui.source_type = 'pack' AND (ui.source_id IN (
            SELECT game_session_id FROM ledger_transactions
            WHERE type = 'pack_opening' AND status = 'completed'
              AND game_session_id IS NOT NULL
              AND (description IS NULL OR description NOT ILIKE '%borrow%')
          )))
          OR (ui.source_type = 'battle' AND ui.source_id IN (SELECT game_session_id FROM non_borrow_battle_sessions))
        )
    ),
    retained AS (
      SELECT cohort, period_index, COUNT(DISTINCT user_id)::text AS retained_count,
        COALESCE(SUM(ABS(amount::numeric)), 0)::text AS wager
      FROM activity
      WHERE period_index >= 0
      GROUP BY cohort, period_index
    ),
    payouts AS (
      SELECT cohort, period_index, COALESCE(SUM(payout), 0)::text AS payout
      FROM (
        SELECT cohort, period_index, ABS(amount::numeric) AS payout FROM payout_ledger WHERE period_index >= 0
        UNION ALL
        SELECT cohort, period_index, amount::numeric AS payout FROM payout_inventory WHERE period_index >= 0
      ) combined
      GROUP BY cohort, period_index
    )
    SELECT
      cs.cohort,
      cs.size,
      r.period_index,
      r.retained_count AS retained,
      (COALESCE(r.wager::numeric, 0) - COALESCE(p.payout::numeric, 0))::text AS revenue
    FROM cohort_sizes cs
    LEFT JOIN retained r ON r.cohort = cs.cohort
    LEFT JOIN payouts p ON p.cohort = cs.cohort AND p.period_index = r.period_index
    ORDER BY cs.cohort DESC, r.period_index ASC
  `);

  // Group rows by cohort.
  const byCohort = new Map<
    string,
    { date: Date; size: number; retained: number[]; revenue: number[] }
  >();

  for (const row of rows) {
    const key = row.cohort.toISOString().slice(0, 10);
    let entry = byCohort.get(key);
    if (!entry) {
      entry = {
        date: row.cohort,
        size: Number(row.size),
        retained: Array(MAX_PERIODS).fill(0),
        revenue: Array(MAX_PERIODS).fill(0),
      };
      byCohort.set(key, entry);
    }
    if (row.period_index != null) {
      const idx = Math.max(0, Math.min(MAX_PERIODS - 1, row.period_index));
      entry.retained[idx] += Number(row.retained ?? 0);
      entry.revenue[idx] += Number(row.revenue ?? 0);
    }
  }

  const sorted = Array.from(byCohort.values()).sort(
    (a, b) => b.date.getTime() - a.date.getTime(),
  );
  const capped = sorted.slice(0, MAX_COHORTS).reverse();

  const labelFormatter =
    granularity === "week"
      ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" })
      : new Intl.DateTimeFormat("en-US", { month: "short", year: "numeric" });

  return {
    granularity,
    maxPeriods: MAX_PERIODS,
    rows: capped.map((c) => ({
      cohort: c.date.toISOString().slice(0, 10),
      label: labelFormatter.format(c.date),
      size: c.size,
      retained: c.retained,
      revenue: c.revenue,
    })),
  };
}
