import { Globe2, TrendingDown, TrendingUp, Users } from "lucide-react";
import { KpiTile, SectionHeading } from "@/components/modern-panels";
import { FadeIn } from "@/components/fade-in";
import { EmptyState } from "@/components/empty-state";
import { formatCurrency, formatNumber } from "@/lib/utils/format";
import { safeQuery } from "@/lib/errors/safe-query";
import { TileErrorFallback } from "@/components/tile-error-fallback";
import {
  getAffiliateGeoBreakdown,
  type AffiliateGeoRow,
  type ReferredGeoRow,
} from "@/lib/queries/insights-rewards/affiliate/geo";
import { compareAffiliateGeo } from "@/lib/clickhouse/compare/insights-affiliate-geo";
import {
  insightsRewardsPeriodLabel,
  type InsightsRewardsPeriod,
} from "@/lib/queries/insights-rewards/_period";

/**
 * Geo distribution lens — two side-by-side breakdowns:
 *
 *   - Affiliate country  : top 12 countries by commission paid to
 *     affiliates living there. Rose bars (cost).
 *   - Referred-user country : top 12 countries by downstream wager
 *     generated by referred users living there. Emerald bars (wager
 *     is house-positive).
 *
 * Useful for geo-targeted promo planning — see where the affiliate
 * program reaches vs where the referred users actually live.
 */
export async function AffiliateGeoTab({
  period,
}: {
  period: InsightsRewardsPeriod;
}) {
  const { data, error } = await safeQuery(
    () => getAffiliateGeoBreakdown(period),
    null,
    "insights-rewards-affiliate.geo",
  );
  if (error || !data) {
    return (
      <TileErrorFallback
        label="Affiliate — Geo"
        hint="The geo-breakdown query failed. Server logs hold the digest."
        size="panel"
      />
    );
  }
  const label = insightsRewardsPeriodLabel(period);

  void compareAffiliateGeo(period, data);

  if (
    data.affiliateGeo.length === 0 &&
    data.referredGeo.length === 0
  ) {
    return (
      <div className="rounded-2xl border bg-card p-4">
        <EmptyState
          icon={Globe2}
          title={`No geo activity in ${label.toLowerCase()}`}
          description="No commission paid and no downstream wager in this window. Try a longer period."
          compact
        />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <FadeIn>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          <KpiTile
            label="Affiliate countries"
            value={formatNumber(data.affiliateGeo.length)}
            sub="Top 12 by commission"
            icon={Globe2}
            accent="rose"
          />
          <KpiTile
            label="Commission visible"
            value={formatCurrency(data.totalCommission)}
            sub={label}
            icon={TrendingDown}
            accent="rose"
          />
          <KpiTile
            label="Referred countries"
            value={formatNumber(data.referredGeo.length)}
            sub="Top 12 by wager"
            icon={Users}
            accent="emerald"
          />
          <KpiTile
            label="Wager visible"
            value={formatCurrency(data.totalDownstreamWager)}
            sub={label}
            icon={TrendingUp}
            accent="emerald"
          />
        </div>
      </FadeIn>

      <FadeIn>
        <div className="grid gap-4 xl:grid-cols-2">
          <div>
            <SectionHeading
              icon={Globe2}
              title="Affiliate country · commission paid"
            />
            <div className="mt-3">
              {data.affiliateGeo.length === 0 ? (
                <EmptyPanel label="No commission paid in window" />
              ) : (
                <AffiliateGeoPanel rows={data.affiliateGeo} />
              )}
            </div>
          </div>
          <div>
            <SectionHeading
              icon={Users}
              title="Referred-user country · downstream wager"
            />
            <div className="mt-3">
              {data.referredGeo.length === 0 ? (
                <EmptyPanel label="No downstream wager in window" />
              ) : (
                <ReferredGeoPanel rows={data.referredGeo} />
              )}
            </div>
          </div>
        </div>
      </FadeIn>
    </div>
  );
}

function AffiliateGeoPanel({ rows }: { rows: AffiliateGeoRow[] }) {
  return (
    <div className="space-y-2 rounded-2xl border bg-card p-4 sm:p-5">
      {rows.map((row) => (
        <div key={row.code} className="rounded-lg border bg-muted/20 p-3">
          <div className="flex items-center justify-between gap-3">
            <div className="flex min-w-0 items-center gap-2">
              <span className="rounded bg-muted px-1.5 py-0.5 text-[10px] font-mono uppercase">
                {row.code}
              </span>
              <span className="shrink-0 text-[11px] tabular-nums text-muted-foreground">
                · {formatNumber(row.affiliateCount)} affiliates
              </span>
            </div>
            <span className="shrink-0 text-sm font-medium tabular-nums text-rose-600 dark:text-rose-400">
              {formatCurrency(row.commission)}
            </span>
          </div>
          <div className="mt-2 flex items-center gap-2">
            <div className="h-2 flex-1 overflow-hidden rounded-sm bg-muted">
              <div
                className="h-full rounded-sm bg-rose-500/60 transition-all"
                style={{ width: `${row.share}%` }}
              />
            </div>
            <span className="shrink-0 text-[11px] tabular-nums text-muted-foreground">
              {row.share.toFixed(1)}%
            </span>
          </div>
        </div>
      ))}
    </div>
  );
}

function ReferredGeoPanel({ rows }: { rows: ReferredGeoRow[] }) {
  return (
    <div className="space-y-2 rounded-2xl border bg-card p-4 sm:p-5">
      {rows.map((row) => (
        <div key={row.code} className="rounded-lg border bg-muted/20 p-3">
          <div className="flex items-center justify-between gap-3">
            <div className="flex min-w-0 items-center gap-2">
              <span className="rounded bg-muted px-1.5 py-0.5 text-[10px] font-mono uppercase">
                {row.code}
              </span>
              <span className="shrink-0 text-[11px] tabular-nums text-muted-foreground">
                · {formatNumber(row.referredUserCount)} users
              </span>
            </div>
            <span className="shrink-0 text-sm font-medium tabular-nums text-emerald-600 dark:text-emerald-400">
              {formatCurrency(row.downstreamWager)}
            </span>
          </div>
          <div className="mt-2 flex items-center gap-2">
            <div className="h-2 flex-1 overflow-hidden rounded-sm bg-muted">
              <div
                className="h-full rounded-sm bg-emerald-500/60 transition-all"
                style={{ width: `${row.share}%` }}
              />
            </div>
            <span className="shrink-0 text-[11px] tabular-nums text-muted-foreground">
              {row.share.toFixed(1)}%
            </span>
          </div>
        </div>
      ))}
    </div>
  );
}

function EmptyPanel({ label }: { label: string }) {
  return (
    <div className="rounded-2xl border bg-card p-6 text-center text-xs text-muted-foreground">
      {label}
    </div>
  );
}
