import "server-only";

import { unstable_cache } from "next/cache";
import { getDb } from "@/lib/db";
import { Prisma } from "@/generated/prisma/client";
import { toNumber } from "@/lib/utils/decimal";
import { getExcludedUserIds } from "@/lib/excluded-users/fetch";
import { blacklistNotInClause } from "@/lib/queries/_blacklist";
import { getCreatorSessionWindowsCte } from "@/lib/queries/creator-session-windows";
import {
  WAGER_TYPES_SQL,
  PAYOUT_TYPES_SQL,
} from "@/lib/queries/_wager-payout-types";

/**
 * Lifetime Value (LTV) analysis — per-user GGR contribution, deposits,
 * bonus drag, and net P&L, broken down into percentile segments.
 *
 * Percentile segments default to:
 *   • Top 1%      — biggest spenders
 *   • Top 10%
 *   • Top 50%
 *   • Bottom 50%  — long-tail "everyone else"
 *
 * Or segment by signup source (organic / creator-affiliate / regular).
 *
 * Heavy enough that we cross-request cache for 5 minutes (LTV moves
 * slowly anyway — depositors don't materialize in seconds). Cache key
 * includes the blacklist and session-windows CTE so admin edits
 * invalidate immediately.
 */

export type LtvSegmentKey = "percentile" | "source";

export function parseLtvSegment(value: string | undefined): LtvSegmentKey {
  return value === "source" ? "source" : "percentile";
}

export type LtvSegment = {
  key: string;
  label: string;
  users: number;
  deposits: number;
  withdrawals: number;
  wager: number;
  ggrContribution: number; // GGR generated by users in this segment
  bonusDrag: number; // bonuses + payouts they received
  netPnl: number; // house net per-segment (positive = house up)
  avgLtv: number; // ggrContribution / users
  medianLtv: number;
};

export type LtvData = {
  segmentBy: LtvSegmentKey;
  segments: LtvSegment[];
  // Per-user list for the histogram + table at the bottom.
  topUsers: { userId: string; username: string | null; ggr: number; deposits: number; netPnl: number }[];
};

export async function getInsightsLtv(segmentBy: LtvSegmentKey): Promise<LtvData> {
  const excluded = await getExcludedUserIds();
  const blacklistIdNotIn = blacklistNotInClause("u.id", excluded);
  const sessionWindowsCte = await getCreatorSessionWindowsCte();

  const rawRows = await cachedPerUserLtv(blacklistIdNotIn, sessionWindowsCte);
  const rows = rawRows.map((r) => ({
    userId: r.user_id,
    username: r.username,
    role: r.role,
    referredBy: r.referred_by,
    referrerIsCreator: r.referrer_is_creator === "true",
    deposits: toNumber(r.deposits),
    withdrawals: toNumber(r.withdrawals),
    wager: toNumber(r.wager),
    payouts: toNumber(r.payouts),
    bonuses: toNumber(r.bonuses),
  }));

  // Compute per-user GGR contribution = wager − payouts. Net P&L (house POV)
  // mirrors the canonical formula: deposits − withdrawals − payouts. We
  // intentionally don't pull live balances here — the LTV view ranks
  // users by what they've actually contributed to the GGR ledger, not
  // their snapshot solvency. (Snapshot P&L lives on /dashboard.)
  const enriched = rows.map((r) => {
    const ggrContribution = r.wager - r.payouts;
    const netPnl = r.deposits - r.withdrawals - r.payouts - r.bonuses;
    return { ...r, ggrContribution, netPnl };
  });

  // Drop rows where the user has zero activity (deposits, withdrawals,
  // wager, payouts, bonuses ALL zero). These add row count but not
  // signal.
  const active = enriched.filter(
    (r) =>
      r.deposits > 0 || r.withdrawals > 0 || r.wager > 0 || r.payouts > 0 || r.bonuses > 0,
  );

  const sorted = [...active].sort((a, b) => b.ggrContribution - a.ggrContribution);

  let segments: LtvSegment[];
  if (segmentBy === "percentile") {
    const total = sorted.length;
    if (total === 0) {
      segments = [];
    } else {
      const top1 = sorted.slice(0, Math.max(1, Math.ceil(total * 0.01)));
      const top10 = sorted.slice(0, Math.max(1, Math.ceil(total * 0.10)));
      const top50 = sorted.slice(0, Math.max(1, Math.ceil(total * 0.50)));
      const bottom50 = sorted.slice(Math.max(1, Math.ceil(total * 0.50)));
      const tail1 = sorted.slice(Math.max(1, Math.ceil(total * 0.01)));
      const tail10 = sorted.slice(Math.max(1, Math.ceil(total * 0.10)));
      segments = [
        summarize("top1", "Top 1%", top1),
        // Rest of top10 (not in top1) so segments are non-overlapping for
        // the visual — but we also report cumulative Top 10% / Top 50% so
        // the admin can read either lens.
        summarize("top10-cum", "Top 10% (cumulative)", top10),
        summarize("top50-cum", "Top 50% (cumulative)", top50),
        summarize("rest-50", "Bottom 50%", bottom50),
        summarize("rest-1", "Excl Top 1%", tail1),
        summarize("rest-10", "Excl Top 10%", tail10),
      ];
    }
  } else {
    // Source segmentation
    const bySource = new Map<string, typeof active>();
    for (const r of active) {
      const key = !r.referredBy
        ? "organic"
        : r.referrerIsCreator
          ? "creator-affiliate"
          : "regular-affiliate";
      const list = bySource.get(key) ?? [];
      list.push(r);
      bySource.set(key, list);
    }
    segments = Array.from(bySource.entries()).map(([key, list]) => {
      const label =
        key === "organic"
          ? "Organic"
          : key === "creator-affiliate"
            ? "Creator affiliate"
            : "Regular affiliate";
      return summarize(key, label, list);
    });
  }

  return {
    segmentBy,
    segments,
    topUsers: sorted.slice(0, 50).map((r) => ({
      userId: r.userId,
      username: r.username,
      ggr: r.ggrContribution,
      deposits: r.deposits,
      netPnl: r.netPnl,
    })),
  };
}

function summarize(
  key: string,
  label: string,
  list: {
    deposits: number;
    withdrawals: number;
    wager: number;
    ggrContribution: number;
    bonuses: number;
    payouts: number;
    netPnl: number;
  }[],
): LtvSegment {
  const users = list.length;
  let deposits = 0;
  let withdrawals = 0;
  let wager = 0;
  let ggrContribution = 0;
  let bonusDrag = 0;
  let netPnl = 0;
  for (const r of list) {
    deposits += r.deposits;
    withdrawals += r.withdrawals;
    wager += r.wager;
    ggrContribution += r.ggrContribution;
    bonusDrag += r.bonuses;
    netPnl += r.netPnl;
  }
  const avgLtv = users > 0 ? ggrContribution / users : 0;
  const sortedAsc = [...list].sort((a, b) => a.ggrContribution - b.ggrContribution);
  const medianLtv =
    users === 0
      ? 0
      : users % 2 === 1
        ? sortedAsc[(users - 1) >> 1].ggrContribution
        : (sortedAsc[users / 2 - 1].ggrContribution + sortedAsc[users / 2].ggrContribution) / 2;
  return {
    key,
    label,
    users,
    deposits,
    withdrawals,
    wager,
    ggrContribution,
    bonusDrag,
    netPnl,
    avgLtv,
    medianLtv,
  };
}

/**
 * One row per real user with the lifetime ledger components needed for
 * LTV. Cross-request cached because the underlying aggregate is heavy
 * (full-ledger scan) and moves on hour boundaries, not seconds.
 *
 * The wager + payout aggregate uses the canonical WAGER_TYPES_SQL /
 * PAYOUT_TYPES_SQL, and drops creator on-stream play via the
 * session_windows CTE — matches the GGR fix landed in 7390363 so the
 * LTV figures sum to the dashboard GGR (over lifetime, modulo the
 * cache TTL).
 */
const cachedPerUserLtv = unstable_cache(
  async (
    blacklistIdNotIn: string,
    sessionWindowsCte: string,
  ): Promise<
    {
      user_id: string;
      username: string | null;
      role: string;
      referred_by: string | null;
      referrer_is_creator: string; // "true" / "false"
      deposits: string;
      withdrawals: string;
      wager: string;
      payouts: string;
      bonuses: string;
    }[]
  > => {
    const db = await getDb();
    const ggrWagerIn = Prisma.raw(WAGER_TYPES_SQL);
    const ggrPayoutIn = Prisma.raw(PAYOUT_TYPES_SQL);
    const bonusTypesSql = Prisma.raw(
      `('deposit_bonus','promo_code_redeemed','gift_card_redeemed','rakeback_claim','affiliate_claim','rain_win','race_prize','creator_tip','waitlist_prize','voucher_redeemed','voucher_exchange','exchange_excess_credit','exchange_excess_to_voucher','battle_excess_to_voucher')`,
    );
    return db.$queryRaw<
      {
        user_id: string;
        username: string | null;
        role: string;
        referred_by: string | null;
        referrer_is_creator: string;
        deposits: string;
        withdrawals: string;
        wager: string;
        payouts: string;
        bonuses: string;
      }[]
    >`
      WITH real_users AS (
        SELECT u.id, u.username, u.role, u.referred_by,
               (CASE WHEN EXISTS (SELECT 1 FROM "user" ref WHERE ref.id = u.referred_by AND ref.role = 'creator')
                     THEN 'true' ELSE 'false' END) AS referrer_is_creator
        FROM "user" u
        WHERE u.role NOT IN ('admin', 'support') ${Prisma.raw(blacklistIdNotIn)}
      ),
      ${Prisma.raw(sessionWindowsCte)},
      base AS (
        SELECT lt.user_id, lt.type, lt.amount::numeric AS amount,
               CASE WHEN ru.role = 'creator'
                    THEN EXISTS (
                      SELECT 1 FROM session_windows sw
                      WHERE sw.uid = lt.user_id
                        AND lt.created_at >= sw.win_start
                        AND lt.created_at <  sw.win_end
                    )
                    ELSE false END AS in_session
        FROM ledger_transactions lt
        JOIN real_users ru ON ru.id = lt.user_id
        WHERE lt.status = 'completed'
      ),
      withdrawal_amounts AS (
        SELECT cwr.user_id, COALESCE(SUM(cwr.total_value_usd::numeric), 0) AS amount
        FROM card_withdrawal_requests cwr
        JOIN real_users ru ON ru.id = cwr.user_id
        WHERE cwr.status IN ('completed', 'shipped')
        GROUP BY cwr.user_id
      )
      SELECT
        ru.id AS user_id,
        ru.username,
        ru.role::text AS role,
        ru.referred_by,
        ru.referrer_is_creator,
        COALESCE(SUM(CASE WHEN b.type = 'deposit' THEN b.amount ELSE 0 END), 0)::text AS deposits,
        COALESCE(MAX(wa.amount), 0)::text AS withdrawals,
        COALESCE(SUM(CASE WHEN b.type IN ${ggrWagerIn} AND NOT b.in_session THEN ABS(b.amount) ELSE 0 END), 0)::text AS wager,
        COALESCE(SUM(CASE WHEN b.type IN ${ggrPayoutIn} AND NOT b.in_session THEN ABS(b.amount) ELSE 0 END), 0)::text AS payouts,
        COALESCE(SUM(CASE WHEN b.type IN ${bonusTypesSql} THEN ABS(b.amount) ELSE 0 END), 0)::text AS bonuses
      FROM real_users ru
      LEFT JOIN base b ON b.user_id = ru.id
      LEFT JOIN withdrawal_amounts wa ON wa.user_id = ru.id
      GROUP BY ru.id, ru.username, ru.role, ru.referred_by, ru.referrer_is_creator
    `;
  },
  ["insights-analytics-per-user-ltv-v1"],
  { revalidate: 300, tags: ["insights-analytics", "dashboard-lifetime"] },
);
