import { unstable_cache } from "next/cache";
import { getDb } from "@/lib/db";
import { blacklistNotInClause } from "@/lib/queries/_blacklist";
import { toNumber } from "@/lib/utils/decimal";
import { CACHE_TAG, loadBlacklist } from "./_shared";
import { resolveAdminRead } from "@/lib/clickhouse/resolve-read";
import { getAffiliateLifetimeRoiFromClickHouse } from "@/lib/clickhouse/queries/insights-rewards/affiliate/lifetime-roi";

/**
 * Lifetime ROI per affiliate.
 *
 * For the top affiliates by total commission paid (lifetime), we
 * compute "are we making money on this affiliate?" by comparing
 * lifetime commission paid against lifetime downstream wager
 * generated by their referred cohort.
 *
 * Source:
 *   - `affiliate_accounts` denormalised counters
 *     (total_paid_out_usd, total_wager_volume_usd, total_referred).
 *
 * These counters are maintained by the platform's affiliate worker —
 * they represent the lifetime view of an affiliate's contribution.
 * That's the right altitude for this lens because we want lifetime
 * ROI not window ROI.
 *
 * House-POV:
 *   - downstream wager is a proxy for cohort activity. The actual
 *     GGR isn't tracked here per-affiliate (the platform sums
 *     wager but not session-level house edge per referral), so we
 *     surface wager directly. The marginal GGR rate is roughly
 *     2–4% so admins can apply that mental multiplier; we don't
 *     try to fake a precision we don't have.
 *   - ROI proxy = wager - commission. Positive = emerald (cohort
 *     generated more wager than we paid them — the program is
 *     net-positive for the house). Negative = rose.
 *
 * Top 25 affiliates by lifetime commission paid so the page focuses
 * on the affiliates that account for the largest house cost.
 */

const ROW_LIMIT = 25;

export type LifetimeRoiRow = {
  affiliateUserId: string;
  username: string | null;
  totalReferred: number;
  /** affiliate_accounts.total_paid_out_usd — lifetime commission settled. */
  lifetimeCommissionPaid: number;
  /** affiliate_accounts.available_usd — accrued but unsettled. */
  lifetimeAccruedAvailable: number;
  /** affiliate_accounts.total_earned_usd — paid + accrued (gross). */
  lifetimeEarnedGross: number;
  /** affiliate_accounts.total_wager_volume_usd — cohort wager lifetime. */
  lifetimeDownstreamWager: number;
  /**
   * ROI proxy = wager - earned. Positive = house net-positive on this
   * affiliate (cohort generated more wager than we paid them, ignoring
   * deposits/withdrawals/won-back). Negative = house net-negative.
   */
  roiProxyUsd: number;
  /** lifetimeEarnedGross / lifetimeDownstreamWager. Null when wager is 0. */
  commissionPctOfWager: number | null;
};

async function compute(blacklistIds: string[]): Promise<LifetimeRoiRow[]> {
  const db = await getDb();
  const blacklistJoin = blacklistNotInClause("u.id", blacklistIds);

  const rows = await db.$queryRawUnsafe<
    {
      affiliate_user_id: string;
      username: string | null;
      total_referred: string;
      total_paid_out: string;
      available: string;
      total_earned: string;
      total_wager: string;
    }[]
  >(`
    SELECT
      aa.user_id AS affiliate_user_id,
      u.username,
      aa.total_referred::text AS total_referred,
      aa.total_paid_out_usd::text AS total_paid_out,
      aa.available_usd::text AS available,
      aa.total_earned_usd::text AS total_earned,
      aa.total_wager_volume_usd::text AS total_wager
    FROM affiliate_accounts aa
    JOIN "user" u ON u.id = aa.user_id
    WHERE u.role NOT IN ('admin', 'support') ${blacklistJoin}
      AND aa.total_paid_out_usd > 0
    ORDER BY aa.total_paid_out_usd DESC
    LIMIT ${ROW_LIMIT}
  `);

  return rows.map((r) => {
    const totalEarned = toNumber(r.total_earned);
    const totalWager = toNumber(r.total_wager);
    return {
      affiliateUserId: r.affiliate_user_id,
      username: r.username,
      totalReferred: Number(r.total_referred),
      lifetimeCommissionPaid: toNumber(r.total_paid_out),
      lifetimeAccruedAvailable: toNumber(r.available),
      lifetimeEarnedGross: totalEarned,
      lifetimeDownstreamWager: totalWager,
      roiProxyUsd: totalWager - totalEarned,
      commissionPctOfWager:
        totalWager > 0 ? (totalEarned / totalWager) * 100 : null,
    };
  });
}

// Lifetime helper is period-agnostic and slow-changing → cache 5 min.
const cached = unstable_cache(
  async (blacklistIds: string[]) => compute(blacklistIds),
  ["insights-affiliate-lifetime-roi-v1"],
  { revalidate: 300, tags: [CACHE_TAG, "rewards-analytics"] },
);

export async function getAffiliateLifetimeRoi(): Promise<LifetimeRoiRow[]> {
  const blacklist = await loadBlacklist();
  return resolveAdminRead<LifetimeRoiRow[]>("insights_affiliate_lifetime_roi", {
    pg: () => cached(blacklist),
    ch: () => getAffiliateLifetimeRoiFromClickHouse(blacklist),
  });
}
