import { blacklistNotInSql, daysAgoFilter, queryRows, sql } from "@/lib/queries/insights-rewards/_drizzle-query";
import { getReadDrizzleDb } from "@/lib/db";
import { toNumber } from "@/lib/utils/decimal";
import {
  daysForInsightsPeriod,
  type InsightsRewardsPeriod,
} from "@/lib/queries/insights-rewards/_period";
import { makeCachedPair } from "@/lib/queries/insights-rewards/_cache";
import { RAKEBACK_CACHE_TAGS } from "@/lib/queries/insights-rewards/rakeback/_cache-tags";
import {
  LIFETIME_PAIRING_LOOKBACK_DAYS,
} from "@/lib/queries/insights-rewards/deposit-bonus/_shared";
import {
  RAKEBACK_ROI_LOOKBACK_DEFAULT,
  type RakebackRoiLookback,
} from "@/app/(admin)/insights/_shared/rakeback-constants";

// Re-export the client-safe lookback constants/helpers so server callers
// can keep importing them from this module. The runtime values live in
// `_constants.ts` (no server imports) so the `"use client"` lookback
// filter can use them without pulling this server-only module into the
// client bundle.
export {
  RAKEBACK_ROI_LOOKBACK_DEFAULT,
  RAKEBACK_ROI_LOOKBACK_OPTIONS,
  parseRakebackRoiLookback,
} from "@/app/(admin)/insights/_shared/rakeback-constants";
export type { RakebackRoiLookback } from "@/app/(admin)/insights/_shared/rakeback-constants";

/**
 * Rakeback ROI — rakeback cost in window vs subsequent gameplay GGR
 * generated by claimants.
 *
 * Cost: SUM(rakeback_amount_usd) in window.
 * Subsequent GGR: each claimant's wager-side − payout-side ledger rows
 *                 that landed AFTER their first rakeback claim in the
 *                 window, within `lookbackDays`. Lifetime windows score
 *                 the forward history bounded to the last
 *                 {@link LIFETIME_PAIRING_LOOKBACK_DAYS} days (see the
 *                 perf note on `lookbackClause` below).
 *
 * Wager / payout match `getGgrBreakdown`:
 *   wagers   = pack_opening + battle_bet + battle_sponsorship + upgrader_bet
 *   payouts  = battle_refund + upgrader_payout
 *
 * House-POV: positive ROI = emerald (cost recouped), negative = rose
 * (we bled cost without recouping). Component picks colour at render.
 *
 * Lookback default = 14 days. Caller can override.
 *
 * Staff + blacklist excluded.
 */

const WAGER_TYPES_SQL = `(
  'pack_opening','battle_bet','battle_sponsorship','upgrader_bet'
)`;
const PAYOUT_TYPES_SQL = `('battle_refund','upgrader_payout')`;

export type RakebackRoi = {
  /** Rakeback cost paid out in window. */
  cost: number;
  /** Claimants' subsequent wager — net of payouts. */
  subsequentGgr: number;
  /** subsequentGgr / cost ratio. `null` when cost is zero. */
  roiRatio: number | null;
  /** Subsequent net: subsequentGgr − cost. House-POV: positive = recovered. */
  netReturn: number;
  /** Distinct claimants the ROI was measured against. */
  claimants: number;
  /**
   * Lookback used (days). Finite windows report the effective per-claimant
   * forward window; lifetime reports {@link LIFETIME_PAIRING_LOOKBACK_DAYS}
   * (the bound applied to the forward scan), never `null`.
   */
  lookbackDays: number | null;
};

async function computeRoi(
  period: InsightsRewardsPeriod,
  lookbackDays: RakebackRoiLookback,
  blacklistIds: string[],
): Promise<RakebackRoi> {
  const db = await getReadDrizzleDb();
  const days = daysForInsightsPeriod(period);
  const blacklistJoin = blacklistNotInSql("u.id", blacklistIds);
  const dateFilter = daysAgoFilter("rc.claimed_at", days);
  // For very short windows we collapse the lookback to the period itself
  // so the math stays bounded (a 24h period with 14d lookback would let
  // unrelated future activity bleed into the comparison).
  const effectiveLookback =
    days !== null && days <= 3 ? Math.max(days, 1) : lookbackDays;
  // Forward-play bound. Finite windows cap the per-claimant forward scan to
  // `first_claim_at + effectiveLookback`. The lifetime (`all`) window used
  // to leave this EMPTY, so `forward_play` LEFT-JOINed every later ledger
  // row per claimant with no upper bound — the heaviest plan on this surface
  // and the one most likely to actually hang in prod. Mirror the deposit-bonus
  // precedent (`windowDateFilterCapped`, bounds lifetime scans to
  // LIFETIME_PAIRING_LOOKBACK_DAYS=365): on lifetime, bound the forward scan
  // to the last 365 days of ledger activity (`lt.created_at >= NOW() - 365d`,
  // applied on top of the existing `>= fc.first_claim_at` floor) so a
  // lifetime view never triggers a full-history scan. Reported `lookbackDays`
  // surfaces 365 on lifetime (was `null`) so the bound is honest in the UI.
  const lookbackClause =
    days !== null
      ? sql`AND lt.created_at <= fc.first_claim_at + (${effectiveLookback} * INTERVAL '1 day')`
      : daysAgoFilter("lt.created_at", LIFETIME_PAIRING_LOOKBACK_DAYS);

  const rows = await queryRows<
    {
      cost: string;
      claimants: string;
      wager: string;
      payouts: string;
    }[]
  >(db, sql`
    WITH first_claim AS (
      SELECT rc.user_id, MIN(rc.claimed_at) AS first_claim_at
      FROM rakeback_claims rc
      JOIN "user" u ON u.id = rc.user_id
      WHERE rc.claimed_at IS NOT NULL
        AND u.role NOT IN ('admin', 'support', 'creator') ${blacklistJoin}
        ${dateFilter}
      GROUP BY rc.user_id
    ),
    cost_per AS (
      SELECT
        rc.user_id,
        SUM(rc.rakeback_amount_usd::numeric) AS rake
      FROM rakeback_claims rc
      JOIN "user" u ON u.id = rc.user_id
      WHERE rc.claimed_at IS NOT NULL
        AND u.role NOT IN ('admin', 'support', 'creator') ${blacklistJoin}
        ${dateFilter}
      GROUP BY rc.user_id
    ),
    forward_play AS (
      SELECT
        fc.user_id,
        COALESCE(SUM(CASE WHEN lt.type::text IN ${sql.raw(WAGER_TYPES_SQL)} THEN ABS(lt.amount::numeric) ELSE 0 END), 0) AS wager,
        COALESCE(SUM(CASE WHEN lt.type::text IN ${sql.raw(PAYOUT_TYPES_SQL)} THEN ABS(lt.amount::numeric) ELSE 0 END), 0) AS payouts
      FROM first_claim fc
      LEFT JOIN ledger_transactions lt
        ON lt.user_id = fc.user_id
       AND lt.status = 'completed'
       AND lt.created_at >= fc.first_claim_at
       AND lt.type IN (${sql.raw(WAGER_TYPES_SQL.slice(1, -1))},${sql.raw(PAYOUT_TYPES_SQL.slice(1, -1))})
       ${lookbackClause}
      GROUP BY fc.user_id
    )
    SELECT
      COALESCE(SUM(cp.rake), 0)::text AS cost,
      COUNT(DISTINCT cp.user_id)::text AS claimants,
      COALESCE(SUM(fp.wager), 0)::text AS wager,
      COALESCE(SUM(fp.payouts), 0)::text AS payouts
    FROM cost_per cp
    LEFT JOIN forward_play fp ON fp.user_id = cp.user_id
  `);

  const r = rows[0];
  const cost = toNumber(r?.cost);
  const wager = toNumber(r?.wager);
  const payouts = toNumber(r?.payouts);
  const claimants = Number(r?.claimants ?? 0);
  const subsequentGgr = wager - payouts;
  const roiRatio = cost > 0 ? subsequentGgr / cost : null;
  const netReturn = subsequentGgr - cost;

  return {
    cost,
    subsequentGgr,
    roiRatio,
    netReturn,
    claimants,
    lookbackDays: days === null ? LIFETIME_PAIRING_LOOKBACK_DAYS : effectiveLookback,
  };
}

// Shared 60s/300s cache pair, keyed on `(period, lookbackDays, blacklist)`.
// The lookback selector stays part of the cache key (an extra key dimension
// threaded through `makeCachedPair`), so each `?lookback=` value caches
// independently — identical behaviour to the hand-rolled pair this replaces.
const cachedRoi = makeCachedPair(
  computeRoi,
  "insights-rewards-rakeback-roi",
  RAKEBACK_CACHE_TAGS,
);

export async function getRakebackRoi(
  period: InsightsRewardsPeriod,
  lookbackDays: RakebackRoiLookback = RAKEBACK_ROI_LOOKBACK_DEFAULT,
): Promise<RakebackRoi> {
  return cachedRoi(period, lookbackDays);
}
