import { unstable_cache } from "next/cache";
import { getDb } from "@/lib/db";
import { getExcludedUserIds } from "@/lib/excluded-users/fetch";
import { blacklistNotInClause } from "@/lib/queries/_blacklist";
import { toNumber } from "@/lib/utils/decimal";
import {
  daysForInsightsPeriod,
  cacheTtlForInsightsPeriod,
  type InsightsRewardsPeriod,
} from "@/lib/queries/insights-rewards/_period";
import {
  RAKEBACK_ROI_LOOKBACK_DEFAULT,
  type RakebackRoiLookback,
} from "@/app/(admin)/insights/rewards/rakeback/_constants";

// Re-export the client-safe lookback constants/helpers so server callers
// can keep importing them from this module. The runtime values live in
// `_constants.ts` (no server imports) so the `"use client"` lookback
// filter can use them without pulling this server-only module into the
// client bundle.
export {
  RAKEBACK_ROI_LOOKBACK_DEFAULT,
  RAKEBACK_ROI_LOOKBACK_OPTIONS,
  parseRakebackRoiLookback,
} from "@/app/(admin)/insights/rewards/rakeback/_constants";
export type { RakebackRoiLookback } from "@/app/(admin)/insights/rewards/rakeback/_constants";

/**
 * Rakeback ROI — rakeback cost in window vs subsequent gameplay GGR
 * generated by claimants.
 *
 * Cost: SUM(rakeback_amount_usd) in window.
 * Subsequent GGR: each claimant's wager-side − payout-side ledger rows
 *                 that landed AFTER their first rakeback claim in the
 *                 window, within `lookbackDays`. Lifetime windows use
 *                 the full forward history per claimant.
 *
 * Wager / payout match `getGgrBreakdown`:
 *   wagers   = pack_opening + battle_bet + battle_sponsorship + upgrader_bet
 *   payouts  = battle_refund + upgrader_payout
 *
 * House-POV: positive ROI = emerald (cost recouped), negative = rose
 * (we bled cost without recouping). Component picks colour at render.
 *
 * Lookback default = 14 days. Caller can override.
 *
 * Staff + blacklist excluded.
 */

const WAGER_TYPES_SQL = `(
  'pack_opening','battle_bet','battle_sponsorship','upgrader_bet'
)`;
const PAYOUT_TYPES_SQL = `('battle_refund','upgrader_payout')`;

export type RakebackRoi = {
  /** Rakeback cost paid out in window. */
  cost: number;
  /** Claimants' subsequent wager — net of payouts. */
  subsequentGgr: number;
  /** subsequentGgr / cost ratio. `null` when cost is zero. */
  roiRatio: number | null;
  /** Subsequent net: subsequentGgr − cost. House-POV: positive = recovered. */
  netReturn: number;
  /** Distinct claimants the ROI was measured against. */
  claimants: number;
  /** Lookback used (days), or `null` for lifetime windows. */
  lookbackDays: number | null;
};

async function computeRoi(
  period: InsightsRewardsPeriod,
  lookbackDays: RakebackRoiLookback,
  blacklistIds: string[],
): Promise<RakebackRoi> {
  const db = await getDb();
  const days = daysForInsightsPeriod(period);
  const blacklistJoin = blacklistNotInClause("u.id", blacklistIds);
  const dateFilter =
    days !== null ? `AND rc.claimed_at >= NOW() - INTERVAL '${days} days'` : "";
  // For very short windows we collapse the lookback to the period itself
  // so the math stays bounded (a 24h period with 14d lookback would let
  // unrelated future activity bleed into the comparison).
  const effectiveLookback =
    days !== null && days <= 3 ? Math.max(days, 1) : lookbackDays;
  const lookbackClause =
    days !== null
      ? `AND lt.created_at <= fc.first_claim_at + INTERVAL '${effectiveLookback} days'`
      : "";

  const rows = await db.$queryRawUnsafe<
    {
      cost: string;
      claimants: string;
      wager: string;
      payouts: string;
    }[]
  >(`
    WITH first_claim AS (
      SELECT rc.user_id, MIN(rc.claimed_at) AS first_claim_at
      FROM rakeback_claims rc
      JOIN "user" u ON u.id = rc.user_id
      WHERE rc.claimed_at IS NOT NULL
        AND u.role NOT IN ('admin', 'support') ${blacklistJoin}
        ${dateFilter}
      GROUP BY rc.user_id
    ),
    cost_per AS (
      SELECT
        rc.user_id,
        SUM(rc.rakeback_amount_usd::numeric) AS rake
      FROM rakeback_claims rc
      JOIN "user" u ON u.id = rc.user_id
      WHERE rc.claimed_at IS NOT NULL
        AND u.role NOT IN ('admin', 'support') ${blacklistJoin}
        ${dateFilter}
      GROUP BY rc.user_id
    ),
    forward_play AS (
      SELECT
        fc.user_id,
        COALESCE(SUM(CASE WHEN lt.type IN ${WAGER_TYPES_SQL} THEN ABS(lt.amount::numeric) ELSE 0 END), 0) AS wager,
        COALESCE(SUM(CASE WHEN lt.type IN ${PAYOUT_TYPES_SQL} THEN ABS(lt.amount::numeric) ELSE 0 END), 0) AS payouts
      FROM first_claim fc
      LEFT JOIN ledger_transactions lt
        ON lt.user_id = fc.user_id
       AND lt.status = 'completed'
       AND lt.created_at >= fc.first_claim_at
       AND lt.type IN (${WAGER_TYPES_SQL.slice(1, -1)},${PAYOUT_TYPES_SQL.slice(1, -1)})
       ${lookbackClause}
      GROUP BY fc.user_id
    )
    SELECT
      COALESCE(SUM(cp.rake), 0)::text AS cost,
      COUNT(DISTINCT cp.user_id)::text AS claimants,
      COALESCE(SUM(fp.wager), 0)::text AS wager,
      COALESCE(SUM(fp.payouts), 0)::text AS payouts
    FROM cost_per cp
    LEFT JOIN forward_play fp ON fp.user_id = cp.user_id
  `);

  const r = rows[0];
  const cost = toNumber(r?.cost);
  const wager = toNumber(r?.wager);
  const payouts = toNumber(r?.payouts);
  const claimants = Number(r?.claimants ?? 0);
  const subsequentGgr = wager - payouts;
  const roiRatio = cost > 0 ? subsequentGgr / cost : null;
  const netReturn = subsequentGgr - cost;

  return {
    cost,
    subsequentGgr,
    roiRatio,
    netReturn,
    claimants,
    lookbackDays: days === null ? null : effectiveLookback,
  };
}

const cachedShort = unstable_cache(
  async (
    period: InsightsRewardsPeriod,
    lookbackDays: RakebackRoiLookback,
    blacklistIds: string[],
  ) => computeRoi(period, lookbackDays, blacklistIds),
  ["insights-rewards-rakeback-roi-v1"],
  { revalidate: 60, tags: ["rewards-analytics", "insights-rewards-rakeback"] },
);

const cachedLong = unstable_cache(
  async (
    period: InsightsRewardsPeriod,
    lookbackDays: RakebackRoiLookback,
    blacklistIds: string[],
  ) => computeRoi(period, lookbackDays, blacklistIds),
  ["insights-rewards-rakeback-roi-lifetime-v1"],
  { revalidate: 300, tags: ["rewards-analytics", "insights-rewards-rakeback"] },
);

export async function getRakebackRoi(
  period: InsightsRewardsPeriod,
  lookbackDays: RakebackRoiLookback = RAKEBACK_ROI_LOOKBACK_DEFAULT,
): Promise<RakebackRoi> {
  const blacklist = await getExcludedUserIds();
  const sorted = [...blacklist].sort();
  return cacheTtlForInsightsPeriod(period) >= 300
    ? cachedLong(period, lookbackDays, sorted)
    : cachedShort(period, lookbackDays, sorted);
}
