import "server-only";

import { getDb } from "@/lib/db";
import { toNumber } from "@/lib/utils/decimal";
import { WAGER_TYPES_SQL } from "@/lib/queries/_wager-payout-types";
import { getExcludedUserIds } from "@/lib/excluded-users/fetch";

/**
 * Per-period House P&L for a single creator's referrals — same canonical
 * formula as the lifetime Platform-P&L on the dashboard / user-detail
 * page, evaluated as DELTAS over the window:
 *
 *   pnl = deposits − withdrawals − balanceChange − inventoryChange − voucherChange
 *
 * Each component is the change over the window. Because lifetime PnL is
 * cash_in − cash_out − liability_now, the windowed delta equals
 * lifetime_pnl(t_end) − lifetime_pnl(t_start). So per-creator cards
 * surface the same formula the dashboard's "Lifetime PnL" surfaces,
 * just scoped to a window and to this creator's referred users.
 *
 * Referred-user pool excludes admin / support / creator roles AND the
 * creator's own user_id — so other streamers' on-site activity (their
 * giveaways, their personal play) doesn't skew the per-creator PnL.
 *
 * House POV: positive (emerald) = we made money, negative (rose) = we lost money.
 */
export type CreatorPnlByPeriod = {
  /** Real cash deposits in the window (lt.type='deposit'). */
  deposits: number;
  /**
   * Cash + cards leaving the house in the window:
   *   ledger withdrawals (lt.type='withdrawal', ABS) +
   *   card_withdrawal_requests.total_value_usd for status in
   *   ('completed','shipped') with COALESCE(shipped_at, completed_at)
   *   in window.
   */
  withdrawals: number;
  /**
   * Net change in user balance over the window (= sum of every
   * completed ledger.amount in window). Positive = we owe MORE
   * balance.
   */
  balanceChange: number;
  /**
   * Net change in unsold-inventory liability over the window
   * (value_at_obtained obtained_at IN window − sold/exchanged IN
   * window). Positive = we owe MORE inventory.
   */
  inventoryChange: number;
  /**
   * Net change in unclaimed-voucher liability over the window
   * (issued IN window − claimed IN window). Positive = we owe MORE
   * voucher value.
   */
  voucherChange: number;
  /**
   * House P&L for the window — same formula the dashboard's Lifetime
   * PnL uses, evaluated per window.
   */
  pnl: number;
};

export type CreatorCodeAndWager = {
  /**
   * Code this creator OWNS. Sourced from the affiliate_codes table
   * (the canonical home for code ownership), NOT user.affiliate_code
   * — that field is the referral COOKIE the user is carrying (the
   * code they USED at signup), per the schema note in
   * src/lib/queries/creators-detail.ts:58. The /creators/[id]
   * detail page already uses the oldest affiliate_codes row as the
   * creator's primary code; this helper now matches so the list
   * card and the detail page agree.
   */
  code: string | null;
  /**
   * affiliate_accounts.total_wager_volume_usd — total wager volume
   * generated by users this creator referred. Same metric the
   * /creators/[id] detail page surfaces as "Wager Volume".
   */
  wagerVolumeUsd: number;
  /**
   * Total signup count — `user` rows with `referred_by = creator.id`.
   * Same number the /creators/[id] page shows as "Signups".
   */
  signups: number;
  /**
   * Lifetime first-time depositors — distinct referred users who have
   * `balances.total_deposited > 0`. Joined through
   * `affiliate_code_usages` to match the /creators/[id] FTD count
   * (the "all" bucket of `ftdByPeriod`).
   */
  ftds: number;
  /**
   * 3-day rolling deposit volume from this creator's affiliates.
   * Source: ledger_transactions of type='deposit' from referred
   * users (admin/support/creator excluded), last 72h. Pulled from
   * the same per-period record as the PnL strip so the displayed
   * row + the displayed PnL never disagree.
   */
  deposits3dUsd: number;
  /**
   * 3-day rolling wager volume — wager-type ledger transactions
   * (pack_opening / battle_bet / battle_sponsorship /
   * withdrawal_shipping_fee) from referred users in the last 72h.
   * Informational only (does not feed the PnL formula); shown next
   * to deposits3dUsd in the row's momentum line.
   */
  wagers3dUsd: number;
  /**
   * Per-period House P&L from this creator's referrals — same
   * canonical balance-sheet formula as the dashboard's Lifetime PnL,
   * evaluated as deltas over each window. Positive = house gain,
   * negative = house loss. Drives the per-card PnL strip on /creators.
   */
  pnlByPeriod: {
    "1d": CreatorPnlByPeriod;
    "3d": CreatorPnlByPeriod;
    "7d": CreatorPnlByPeriod;
    "14d": CreatorPnlByPeriod;
    "30d": CreatorPnlByPeriod;
  };
};

const EMPTY_PERIOD: CreatorPnlByPeriod = {
  deposits: 0,
  withdrawals: 0,
  balanceChange: 0,
  inventoryChange: 0,
  voucherChange: 0,
  pnl: 0,
};
const EMPTY_PNL: CreatorCodeAndWager["pnlByPeriod"] = {
  "1d": EMPTY_PERIOD,
  "3d": EMPTY_PERIOD,
  "7d": EMPTY_PERIOD,
  "14d": EMPTY_PERIOD,
  "30d": EMPTY_PERIOD,
};

type LedgerRow = {
  creator_user_id: string;
  deposits_1d: string; deposits_3d: string; deposits_7d: string; deposits_14d: string; deposits_30d: string;
  manual_wd_1d: string; manual_wd_3d: string; manual_wd_7d: string; manual_wd_14d: string; manual_wd_30d: string;
  bal_change_1d: string; bal_change_3d: string; bal_change_7d: string; bal_change_14d: string; bal_change_30d: string;
  wagers_3d: string;
};

type CardWithdrawalRow = {
  creator_user_id: string;
  cwd_1d: string; cwd_3d: string; cwd_7d: string; cwd_14d: string; cwd_30d: string;
};

type InventoryRow = {
  creator_user_id: string;
  obtained_1d: string; obtained_3d: string; obtained_7d: string; obtained_14d: string; obtained_30d: string;
  disposed_1d: string; disposed_3d: string; disposed_7d: string; disposed_14d: string; disposed_30d: string;
};

type VoucherRow = {
  creator_user_id: string;
  issued_1d: string; issued_3d: string; issued_7d: string; issued_14d: string; issued_30d: string;
  claimed_1d: string; claimed_3d: string; claimed_7d: string; claimed_14d: string; claimed_30d: string;
};

/**
 * Fetch (code, wagerVolumeUsd, signups, ftds, momentum, pnlByPeriod) for
 * a list of creator user_ids in batch. Keyed on user_id; missing
 * creators get a zero/null record so callers can `.get(id) ?? EMPTY`
 * without guards.
 *
 * 8 parallel round-trips — none of them N+1.
 */
// Built per-call so the admin-managed blacklist (cached via React
// `cache()`) can append `AND u.id NOT IN (...)` to every per-creator
// referral aggregate. Same convention as `creators-pnl.ts`.
async function buildBlacklistIdNotIn(): Promise<string> {
  const excluded = await getExcludedUserIds();
  return excluded.length > 0
    ? `AND u.id NOT IN (${excluded.map((id) => `'${id.replace(/'/g, "''")}'`).join(",")})`
    : "";
}

export async function getCodeAndWagerByUser(
  userIds: string[],
): Promise<Map<string, CreatorCodeAndWager>> {
  const result = new Map<string, CreatorCodeAndWager>();
  if (userIds.length === 0) return result;

  const db = await getDb();
  const blacklistIdNotIn = await buildBlacklistIdNotIn();
  const [
    codeRows,
    affiliateAccounts,
    signupRows,
    ftdRows,
    ledgerRows,
    cardWithdrawalRows,
    inventoryRows,
    voucherRows,
  ] = await Promise.all([
    // Oldest affiliate_codes row per user_id — the same convention
    // /creators/[id]'s primaryCode uses. DISTINCT ON keeps a single
    // row per user_id with the earliest created_at (= the first code
    // they ever minted).
    db.$queryRawUnsafe<{ user_id: string; code: string }[]>(
      `SELECT DISTINCT ON (user_id) user_id, code
         FROM affiliate_codes
        WHERE user_id = ANY($1::text[])
        ORDER BY user_id, created_at ASC`,
      userIds,
    ),
    db.affiliate_accounts.findMany({
      where: { user_id: { in: userIds } },
      select: { user_id: true, total_wager_volume_usd: true },
    }),
    db.$queryRawUnsafe<{ user_id: string; signups: string }[]>(
      `SELECT referred_by AS user_id, COUNT(*)::text AS signups
         FROM "user"
        WHERE referred_by = ANY($1::text[])
        GROUP BY referred_by`,
      userIds,
    ),
    // Lifetime FTDs per creator: DISTINCT referred users (via
    // affiliate_code_usages.usage_type = 'deposit') who have a
    // non-zero total_deposited on `balances`. Mirrors the "all"
    // bucket of /creators/[id]'s ftdByPeriod query.
    db.$queryRawUnsafe<{ user_id: string; ftds: string }[]>(
      `SELECT acu.affiliate_user_id AS user_id,
              COUNT(DISTINCT acu.referred_user_id)::text AS ftds
         FROM affiliate_code_usages acu
         JOIN balances b
           ON b.user_id = acu.referred_user_id
          AND b.total_deposited > 0
        WHERE acu.affiliate_user_id = ANY($1::text[])
          AND acu.usage_type = 'deposit'
        GROUP BY acu.affiliate_user_id`,
      userIds,
    ),

    // Ledger-derived components per window per creator:
    //   deposits     = SUM(amount where type='deposit')
    //   manual_wd    = SUM(amount where type='admin_balance_adjustment'
    //                       AND balance_after < balance_before
    //                       AND description ILIKE 'Manual withdrawal:%')
    //   bal_change   = SUM(balance_after − balance_before) — SIGNED.
    //
    // Sign convention notes:
    //   • lt.amount is ALWAYS POSITIVE in this DB; the sign of the
    //     balance impact lives in (balance_after − balance_before).
    //   • There is no 'withdrawal' value in ledger_transaction_type.
    //     Real withdrawals are captured by card_withdrawal_requests
    //     (separate table, scanned in the next query) plus the rare
    //     admin_balance_adjustment manual-cashout (description-tagged).
    //
    // The 3d wager total is also pulled here so the row's momentum
    // line + the PnL strip share a single ledger scan. All rows are
    // bounded to the last 30 days so the planner doesn't traverse
    // historical ledger.
    db.$queryRawUnsafe<LedgerRow[]>(
      `WITH creator_referrals AS (
         SELECT DISTINCT acu.affiliate_user_id AS creator_user_id,
                         acu.referred_user_id  AS user_id
           FROM affiliate_code_usages acu
           JOIN "user" u ON u.id = acu.referred_user_id
          WHERE acu.affiliate_user_id = ANY($1::text[])
            AND u.role NOT IN ('admin', 'support', 'creator') ${blacklistIdNotIn}
            AND u.id != acu.affiliate_user_id
       )
       SELECT cr.creator_user_id,
              COALESCE(SUM(CASE WHEN lt.type = 'deposit' AND lt.created_at >= NOW() - INTERVAL '1 day'   THEN lt.amount::numeric ELSE 0 END), 0)::text AS deposits_1d,
              COALESCE(SUM(CASE WHEN lt.type = 'deposit' AND lt.created_at >= NOW() - INTERVAL '3 days'  THEN lt.amount::numeric ELSE 0 END), 0)::text AS deposits_3d,
              COALESCE(SUM(CASE WHEN lt.type = 'deposit' AND lt.created_at >= NOW() - INTERVAL '7 days'  THEN lt.amount::numeric ELSE 0 END), 0)::text AS deposits_7d,
              COALESCE(SUM(CASE WHEN lt.type = 'deposit' AND lt.created_at >= NOW() - INTERVAL '14 days' THEN lt.amount::numeric ELSE 0 END), 0)::text AS deposits_14d,
              COALESCE(SUM(CASE WHEN lt.type = 'deposit' AND lt.created_at >= NOW() - INTERVAL '30 days' THEN lt.amount::numeric ELSE 0 END), 0)::text AS deposits_30d,
              COALESCE(SUM(CASE WHEN lt.type = 'admin_balance_adjustment' AND lt.balance_after < lt.balance_before AND lt.description ILIKE 'Manual withdrawal:%' AND lt.created_at >= NOW() - INTERVAL '1 day'   THEN lt.amount::numeric ELSE 0 END), 0)::text AS manual_wd_1d,
              COALESCE(SUM(CASE WHEN lt.type = 'admin_balance_adjustment' AND lt.balance_after < lt.balance_before AND lt.description ILIKE 'Manual withdrawal:%' AND lt.created_at >= NOW() - INTERVAL '3 days'  THEN lt.amount::numeric ELSE 0 END), 0)::text AS manual_wd_3d,
              COALESCE(SUM(CASE WHEN lt.type = 'admin_balance_adjustment' AND lt.balance_after < lt.balance_before AND lt.description ILIKE 'Manual withdrawal:%' AND lt.created_at >= NOW() - INTERVAL '7 days'  THEN lt.amount::numeric ELSE 0 END), 0)::text AS manual_wd_7d,
              COALESCE(SUM(CASE WHEN lt.type = 'admin_balance_adjustment' AND lt.balance_after < lt.balance_before AND lt.description ILIKE 'Manual withdrawal:%' AND lt.created_at >= NOW() - INTERVAL '14 days' THEN lt.amount::numeric ELSE 0 END), 0)::text AS manual_wd_14d,
              COALESCE(SUM(CASE WHEN lt.type = 'admin_balance_adjustment' AND lt.balance_after < lt.balance_before AND lt.description ILIKE 'Manual withdrawal:%' AND lt.created_at >= NOW() - INTERVAL '30 days' THEN lt.amount::numeric ELSE 0 END), 0)::text AS manual_wd_30d,
              COALESCE(SUM(CASE WHEN lt.created_at >= NOW() - INTERVAL '1 day'   THEN (lt.balance_after - lt.balance_before)::numeric ELSE 0 END), 0)::text AS bal_change_1d,
              COALESCE(SUM(CASE WHEN lt.created_at >= NOW() - INTERVAL '3 days'  THEN (lt.balance_after - lt.balance_before)::numeric ELSE 0 END), 0)::text AS bal_change_3d,
              COALESCE(SUM(CASE WHEN lt.created_at >= NOW() - INTERVAL '7 days'  THEN (lt.balance_after - lt.balance_before)::numeric ELSE 0 END), 0)::text AS bal_change_7d,
              COALESCE(SUM(CASE WHEN lt.created_at >= NOW() - INTERVAL '14 days' THEN (lt.balance_after - lt.balance_before)::numeric ELSE 0 END), 0)::text AS bal_change_14d,
              COALESCE(SUM(CASE WHEN lt.created_at >= NOW() - INTERVAL '30 days' THEN (lt.balance_after - lt.balance_before)::numeric ELSE 0 END), 0)::text AS bal_change_30d,
              COALESCE(SUM(CASE WHEN lt.type IN ${WAGER_TYPES_SQL} AND lt.created_at >= NOW() - INTERVAL '3 days' THEN lt.amount::numeric ELSE 0 END), 0)::text AS wagers_3d
         FROM ledger_transactions lt
         JOIN creator_referrals cr ON cr.user_id = lt.user_id
        WHERE lt.status = 'completed'
          AND lt.created_at >= NOW() - INTERVAL '30 days'
        GROUP BY cr.creator_user_id`,
      userIds,
    ),

    // Card withdrawals per window per creator. Time-scoped on the
    // moment the value left the house (COALESCE shipped, completed).
    db.$queryRawUnsafe<CardWithdrawalRow[]>(
      `WITH creator_referrals AS (
         SELECT DISTINCT acu.affiliate_user_id AS creator_user_id,
                         acu.referred_user_id  AS user_id
           FROM affiliate_code_usages acu
           JOIN "user" u ON u.id = acu.referred_user_id
          WHERE acu.affiliate_user_id = ANY($1::text[])
            AND u.role NOT IN ('admin', 'support', 'creator') ${blacklistIdNotIn}
            AND u.id != acu.affiliate_user_id
       )
       SELECT cr.creator_user_id,
              COALESCE(SUM(CASE WHEN COALESCE(cwr.shipped_at, cwr.completed_at) >= NOW() - INTERVAL '1 day'   THEN cwr.total_value_usd::numeric ELSE 0 END), 0)::text AS cwd_1d,
              COALESCE(SUM(CASE WHEN COALESCE(cwr.shipped_at, cwr.completed_at) >= NOW() - INTERVAL '3 days'  THEN cwr.total_value_usd::numeric ELSE 0 END), 0)::text AS cwd_3d,
              COALESCE(SUM(CASE WHEN COALESCE(cwr.shipped_at, cwr.completed_at) >= NOW() - INTERVAL '7 days'  THEN cwr.total_value_usd::numeric ELSE 0 END), 0)::text AS cwd_7d,
              COALESCE(SUM(CASE WHEN COALESCE(cwr.shipped_at, cwr.completed_at) >= NOW() - INTERVAL '14 days' THEN cwr.total_value_usd::numeric ELSE 0 END), 0)::text AS cwd_14d,
              COALESCE(SUM(CASE WHEN COALESCE(cwr.shipped_at, cwr.completed_at) >= NOW() - INTERVAL '30 days' THEN cwr.total_value_usd::numeric ELSE 0 END), 0)::text AS cwd_30d
         FROM card_withdrawal_requests cwr
         JOIN creator_referrals cr ON cr.user_id = cwr.user_id
        WHERE cwr.status IN ('completed', 'shipped')
          AND COALESCE(cwr.shipped_at, cwr.completed_at) >= NOW() - INTERVAL '30 days'
        GROUP BY cr.creator_user_id`,
      userIds,
    ),

    // Inventory delta per window per creator (value_at_obtained for
    // items obtained / disposed in window). Same valuation Platform-P&L
    // uses on the user-detail page.
    db.$queryRawUnsafe<InventoryRow[]>(
      `WITH creator_referrals AS (
         SELECT DISTINCT acu.affiliate_user_id AS creator_user_id,
                         acu.referred_user_id  AS user_id
           FROM affiliate_code_usages acu
           JOIN "user" u ON u.id = acu.referred_user_id
          WHERE acu.affiliate_user_id = ANY($1::text[])
            AND u.role NOT IN ('admin', 'support', 'creator') ${blacklistIdNotIn}
            AND u.id != acu.affiliate_user_id
       )
       SELECT cr.creator_user_id,
              COALESCE(SUM(CASE WHEN ui.obtained_at >= NOW() - INTERVAL '1 day'   THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS obtained_1d,
              COALESCE(SUM(CASE WHEN ui.obtained_at >= NOW() - INTERVAL '3 days'  THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS obtained_3d,
              COALESCE(SUM(CASE WHEN ui.obtained_at >= NOW() - INTERVAL '7 days'  THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS obtained_7d,
              COALESCE(SUM(CASE WHEN ui.obtained_at >= NOW() - INTERVAL '14 days' THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS obtained_14d,
              COALESCE(SUM(CASE WHEN ui.obtained_at >= NOW() - INTERVAL '30 days' THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS obtained_30d,
              COALESCE(SUM(CASE WHEN (ui.sold_at >= NOW() - INTERVAL '1 day'   OR ui.exchanged_at >= NOW() - INTERVAL '1 day')   THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS disposed_1d,
              COALESCE(SUM(CASE WHEN (ui.sold_at >= NOW() - INTERVAL '3 days'  OR ui.exchanged_at >= NOW() - INTERVAL '3 days')  THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS disposed_3d,
              COALESCE(SUM(CASE WHEN (ui.sold_at >= NOW() - INTERVAL '7 days'  OR ui.exchanged_at >= NOW() - INTERVAL '7 days')  THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS disposed_7d,
              COALESCE(SUM(CASE WHEN (ui.sold_at >= NOW() - INTERVAL '14 days' OR ui.exchanged_at >= NOW() - INTERVAL '14 days') THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS disposed_14d,
              COALESCE(SUM(CASE WHEN (ui.sold_at >= NOW() - INTERVAL '30 days' OR ui.exchanged_at >= NOW() - INTERVAL '30 days') THEN ui.value_at_obtained::numeric ELSE 0 END), 0)::text AS disposed_30d
         FROM user_inventory ui
         JOIN creator_referrals cr ON cr.user_id = ui.user_id
        WHERE (
              ui.obtained_at  >= NOW() - INTERVAL '30 days'
           OR ui.sold_at      >= NOW() - INTERVAL '30 days'
           OR ui.exchanged_at >= NOW() - INTERVAL '30 days'
        )
        GROUP BY cr.creator_user_id`,
      userIds,
    ),

    // Voucher delta per window per creator.
    db.$queryRawUnsafe<VoucherRow[]>(
      `WITH creator_referrals AS (
         SELECT DISTINCT acu.affiliate_user_id AS creator_user_id,
                         acu.referred_user_id  AS user_id
           FROM affiliate_code_usages acu
           JOIN "user" u ON u.id = acu.referred_user_id
          WHERE acu.affiliate_user_id = ANY($1::text[])
            AND u.role NOT IN ('admin', 'support', 'creator') ${blacklistIdNotIn}
            AND u.id != acu.affiliate_user_id
       )
       SELECT cr.creator_user_id,
              COALESCE(SUM(CASE WHEN v.created_at >= NOW() - INTERVAL '1 day'   THEN v.value::numeric ELSE 0 END), 0)::text AS issued_1d,
              COALESCE(SUM(CASE WHEN v.created_at >= NOW() - INTERVAL '3 days'  THEN v.value::numeric ELSE 0 END), 0)::text AS issued_3d,
              COALESCE(SUM(CASE WHEN v.created_at >= NOW() - INTERVAL '7 days'  THEN v.value::numeric ELSE 0 END), 0)::text AS issued_7d,
              COALESCE(SUM(CASE WHEN v.created_at >= NOW() - INTERVAL '14 days' THEN v.value::numeric ELSE 0 END), 0)::text AS issued_14d,
              COALESCE(SUM(CASE WHEN v.created_at >= NOW() - INTERVAL '30 days' THEN v.value::numeric ELSE 0 END), 0)::text AS issued_30d,
              COALESCE(SUM(CASE WHEN v.claimed_at >= NOW() - INTERVAL '1 day'   THEN v.value::numeric ELSE 0 END), 0)::text AS claimed_1d,
              COALESCE(SUM(CASE WHEN v.claimed_at >= NOW() - INTERVAL '3 days'  THEN v.value::numeric ELSE 0 END), 0)::text AS claimed_3d,
              COALESCE(SUM(CASE WHEN v.claimed_at >= NOW() - INTERVAL '7 days'  THEN v.value::numeric ELSE 0 END), 0)::text AS claimed_7d,
              COALESCE(SUM(CASE WHEN v.claimed_at >= NOW() - INTERVAL '14 days' THEN v.value::numeric ELSE 0 END), 0)::text AS claimed_14d,
              COALESCE(SUM(CASE WHEN v.claimed_at >= NOW() - INTERVAL '30 days' THEN v.value::numeric ELSE 0 END), 0)::text AS claimed_30d
         FROM vouchers v
         JOIN creator_referrals cr ON cr.user_id = v.user_id
        WHERE (
              v.created_at >= NOW() - INTERVAL '30 days'
           OR v.claimed_at >= NOW() - INTERVAL '30 days'
        )
        GROUP BY cr.creator_user_id`,
      userIds,
    ),
  ]);

  const codeById = new Map(codeRows.map((r) => [r.user_id, r.code]));
  const wagerById = new Map(
    affiliateAccounts.map((a) => [
      a.user_id,
      toNumber(a.total_wager_volume_usd),
    ]),
  );
  const signupsById = new Map(
    signupRows.map((r) => [r.user_id, Number(r.signups)]),
  );
  const ftdsById = new Map(ftdRows.map((r) => [r.user_id, Number(r.ftds)]));

  // Project the four wide rows (one row per creator from each scan)
  // into a single CreatorPnlByPeriod object per creator per period.
  // Components default to 0 when a creator has no rows from that
  // particular scan (e.g. no card withdrawals in 30 days).
  const cwById = new Map(cardWithdrawalRows.map((r) => [r.creator_user_id, r]));
  const ivById = new Map(inventoryRows.map((r) => [r.creator_user_id, r]));
  const vchById = new Map(voucherRows.map((r) => [r.creator_user_id, r]));

  type PKey = "1d" | "3d" | "7d" | "14d" | "30d";

  const buildForCreator = (creatorId: string): CreatorCodeAndWager["pnlByPeriod"] => {
    const lr = ledgerRows.find((r) => r.creator_user_id === creatorId);
    const cw = cwById.get(creatorId);
    const iv = ivById.get(creatorId);
    const vc = vchById.get(creatorId);

    const computeForPeriod = (period: PKey): CreatorPnlByPeriod => {
      const deposits = lr ? toNumber(lr[`deposits_${period}` as const]) : 0;
      const manualWithdrawals = lr
        ? toNumber(lr[`manual_wd_${period}` as const])
        : 0;
      const cardWithdrawals = cw ? toNumber(cw[`cwd_${period}` as const]) : 0;
      const withdrawals = manualWithdrawals + cardWithdrawals;
      const balanceChange = lr ? toNumber(lr[`bal_change_${period}` as const]) : 0;
      const obtained = iv ? toNumber(iv[`obtained_${period}` as const]) : 0;
      const disposed = iv ? toNumber(iv[`disposed_${period}` as const]) : 0;
      const inventoryChange = obtained - disposed;
      const issued = vc ? toNumber(vc[`issued_${period}` as const]) : 0;
      const claimed = vc ? toNumber(vc[`claimed_${period}` as const]) : 0;
      const voucherChange = issued - claimed;
      const pnl =
        deposits -
        withdrawals -
        balanceChange -
        inventoryChange -
        voucherChange;
      return {
        deposits,
        withdrawals,
        balanceChange,
        inventoryChange,
        voucherChange,
        pnl,
      };
    };

    return {
      "1d": computeForPeriod("1d"),
      "3d": computeForPeriod("3d"),
      "7d": computeForPeriod("7d"),
      "14d": computeForPeriod("14d"),
      "30d": computeForPeriod("30d"),
    };
  };

  // Set of creator IDs that produced ANY rows from the four PnL scans
  // — even one of {ledger, card_withdrawals, inventory, vouchers}.
  // Anyone with no activity at all gets EMPTY_PNL.
  const activeCreatorIds = new Set<string>();
  for (const r of ledgerRows) activeCreatorIds.add(r.creator_user_id);
  for (const r of cardWithdrawalRows) activeCreatorIds.add(r.creator_user_id);
  for (const r of inventoryRows) activeCreatorIds.add(r.creator_user_id);
  for (const r of voucherRows) activeCreatorIds.add(r.creator_user_id);

  for (const id of userIds) {
    const pnl = activeCreatorIds.has(id) ? buildForCreator(id) : EMPTY_PNL;
    result.set(id, {
      code: codeById.get(id) ?? null,
      wagerVolumeUsd: wagerById.get(id) ?? 0,
      signups: signupsById.get(id) ?? 0,
      ftds: ftdsById.get(id) ?? 0,
      // 3d wagers + deposits surface on the existing momentum line —
      // pulled from the per-period record so the row + the PnL
      // strip can never disagree.
      deposits3dUsd: pnl["3d"].deposits,
      // wagers3dUsd is informational (not used in PnL formula); pulled
      // directly from the ledger-side aggregate.
      wagers3dUsd: ledgerRows.find((r) => r.creator_user_id === id)
        ? toNumber(
            ledgerRows.find((r) => r.creator_user_id === id)!.wagers_3d,
          )
        : 0,
      pnlByPeriod: pnl,
    });
  }
  return result;
}
