import "server-only";

import { getDb } from "@/lib/db";
import { toNumber } from "@/lib/utils/decimal";
import {
  WAGER_TYPES_SQL,
  PAYOUT_TYPES_SQL,
} from "@/lib/queries/_wager-payout-types";

/**
 * Per-period PnL snapshot for a single creator. Periods match what the
 * card displays: 1d / 3d / 7d / 14d / 30d. PnL is GGR from this
 * creator's referrals — wagers minus payouts — in house POV. Positive
 * = house income, negative = house loss.
 */
export type CreatorPnlByPeriod = {
  wagers: number;
  payouts: number;
  /** wagers − payouts. Same shape as the dashboard GGR aggregate. */
  pnl: number;
  /** Real deposit volume from referred users in the period (lt.type='deposit'). */
  deposits: number;
};

export type CreatorCodeAndWager = {
  /**
   * Code this creator OWNS. Sourced from the affiliate_codes table
   * (the canonical home for code ownership), NOT user.affiliate_code
   * — that field is the referral COOKIE the user is carrying (the
   * code they USED at signup), per the schema note in
   * src/lib/queries/creators-detail.ts:58. The /creators/[id]
   * detail page already uses the oldest affiliate_codes row as the
   * creator's primary code; this helper now matches so the list
   * card and the detail page agree.
   */
  code: string | null;
  /**
   * affiliate_accounts.total_wager_volume_usd — total wager volume
   * generated by users this creator referred. Same metric the
   * /creators/[id] detail page surfaces as "Wager Volume".
   */
  wagerVolumeUsd: number;
  /**
   * Total signup count — `user` rows with `referred_by = creator.id`.
   * Same number the /creators/[id] page shows as "Signups".
   */
  signups: number;
  /**
   * Lifetime first-time depositors — distinct referred users who have
   * `balances.total_deposited > 0`. Joined through
   * `affiliate_code_usages` to match the /creators/[id] FTD count
   * (the "all" bucket of `ftdByPeriod`).
   */
  ftds: number;
  /**
   * 3-day rolling deposit volume from this creator's affiliates.
   * Source: `ledger_transactions` rows of `type = 'deposit'` from
   * users this creator referred, staff-excluded, last 72h. Used to
   * be `affiliate_code_usages.deposit_amount_usd` which the backend
   * only writes for the FIRST deposit per user (FTD-only) — that
   * was undercounting repeat deposits, hence the migration to the
   * ledger source for the actual cash-in number.
   */
  deposits3dUsd: number;
  /**
   * 3-day rolling wager volume — wager-type ledger transactions
   * (pack_opening / battle_bet / battle_sponsorship /
   * withdrawal_shipping_fee, the canonical wager set) from referred
   * users in the last 72h. Aligned with the per-creator PnL row so
   * the displayed wagers always reconcile against the displayed PnL.
   */
  wagers3dUsd: number;
  /**
   * Per-period PnL from this creator's referrals — wagers minus
   * payouts (GGR). Periods: 1d / 3d / 7d / 14d / 30d. Positive =
   * house gain, negative = house loss. Drives the per-card PnL
   * strip on /creators.
   */
  pnlByPeriod: {
    "1d": CreatorPnlByPeriod;
    "3d": CreatorPnlByPeriod;
    "7d": CreatorPnlByPeriod;
    "14d": CreatorPnlByPeriod;
    "30d": CreatorPnlByPeriod;
  };
};

/** Empty period record — used when a creator has no referred-user ledger activity. */
const EMPTY_PERIOD: CreatorPnlByPeriod = {
  wagers: 0,
  payouts: 0,
  pnl: 0,
  deposits: 0,
};
const EMPTY_PNL: CreatorCodeAndWager["pnlByPeriod"] = {
  "1d": EMPTY_PERIOD,
  "3d": EMPTY_PERIOD,
  "7d": EMPTY_PERIOD,
  "14d": EMPTY_PERIOD,
  "30d": EMPTY_PERIOD,
};

/**
 * Fetch (code, wagerVolumeUsd, signups, ftds) for a list of creator
 * user_ids in batch. Keyed on user_id; missing creators get a
 * zero/null record so callers can `.get(id) ?? EMPTY` without guards.
 *
 * Sources, all main DB:
 *   - affiliate_codes (oldest row per user_id) → code
 *   - affiliate_accounts.total_wager_volume_usd → wagerVolumeUsd
 *   - COUNT(user WHERE referred_by = creator.id) → signups
 *   - COUNT(DISTINCT acu.referred_user_id WHERE balances.total_deposited > 0)
 *       → ftds (matches /creators/[id]'s lifetime FTD count)
 *
 * Four parallel round-trips, no N+1.
 */
export async function getCodeAndWagerByUser(
  userIds: string[],
): Promise<Map<string, CreatorCodeAndWager>> {
  const result = new Map<string, CreatorCodeAndWager>();
  if (userIds.length === 0) return result;

  const db = await getDb();
  const [codeRows, affiliateAccounts, signupRows, ftdRows, momentumRows] =
    await Promise.all([
      // Oldest affiliate_codes row per user_id — the same convention
      // /creators/[id]'s primaryCode uses. DISTINCT ON keeps a single
      // row per user_id with the earliest created_at (= the first code
      // they ever minted).
      db.$queryRawUnsafe<{ user_id: string; code: string }[]>(
        `SELECT DISTINCT ON (user_id) user_id, code
           FROM affiliate_codes
          WHERE user_id = ANY($1::text[])
          ORDER BY user_id, created_at ASC`,
        userIds,
      ),
      db.affiliate_accounts.findMany({
        where: { user_id: { in: userIds } },
        select: { user_id: true, total_wager_volume_usd: true },
      }),
      db.$queryRawUnsafe<{ user_id: string; signups: string }[]>(
        `SELECT referred_by AS user_id, COUNT(*)::text AS signups
           FROM "user"
          WHERE referred_by = ANY($1::text[])
          GROUP BY referred_by`,
        userIds,
      ),
      // Lifetime FTDs per creator: DISTINCT referred users (via
      // affiliate_code_usages.usage_type = 'deposit') who have a
      // non-zero total_deposited on `balances`. Mirrors the "all"
      // bucket of /creators/[id]'s ftdByPeriod query.
      db.$queryRawUnsafe<{ user_id: string; ftds: string }[]>(
        `SELECT acu.affiliate_user_id AS user_id,
                COUNT(DISTINCT acu.referred_user_id)::text AS ftds
           FROM affiliate_code_usages acu
           JOIN balances b
             ON b.user_id = acu.referred_user_id
            AND b.total_deposited > 0
          WHERE acu.affiliate_user_id = ANY($1::text[])
            AND acu.usage_type = 'deposit'
          GROUP BY acu.affiliate_user_id`,
        userIds,
      ),
      // Per-creator PnL + momentum across 5 windows (1d / 3d / 7d /
      // 14d / 30d), batched. Source = ledger_transactions for users
      // referred by this creator (joined via affiliate_code_usages
      // → DISTINCT referred_user_id). Staff (admin / support)
      // excluded. Each period's three SUM-CASE clauses share the
      // same scan, so the planner does one ledger seq/index scan
      // for the whole result no matter how many periods are
      // requested.
      //
      // Why ledger and not affiliate_code_usages: the backend writes
      // acu.deposit_amount_usd for the FTD only; repeat deposits
      // weren't counted. Switching to lt.type='deposit' on referred
      // users counts every cash deposit, which is the number the
      // admin actually wants to see. Wagers + payouts on the same
      // source guarantees the displayed PnL reconciles with the
      // displayed wager number per row.
      db.$queryRawUnsafe<
        Array<
          {
            creator_user_id: string;
          } & Record<
            | "wagers_1d" | "wagers_3d" | "wagers_7d" | "wagers_14d" | "wagers_30d"
            | "payouts_1d" | "payouts_3d" | "payouts_7d" | "payouts_14d" | "payouts_30d"
            | "deposits_1d" | "deposits_3d" | "deposits_7d" | "deposits_14d" | "deposits_30d",
            string
          >
        >
      >(
        `WITH creator_referrals AS (
           SELECT DISTINCT acu.affiliate_user_id AS creator_user_id,
                           acu.referred_user_id  AS user_id
             FROM affiliate_code_usages acu
            WHERE acu.affiliate_user_id = ANY($1::text[])
         )
         SELECT cr.creator_user_id,
                -- Wagers per window — ABS because user-side ledger
                -- amounts are stored negative for debits.
                COALESCE(SUM(CASE WHEN lt.type IN ${WAGER_TYPES_SQL}  AND lt.created_at >= NOW() - INTERVAL '1 day'   THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS wagers_1d,
                COALESCE(SUM(CASE WHEN lt.type IN ${WAGER_TYPES_SQL}  AND lt.created_at >= NOW() - INTERVAL '3 days'  THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS wagers_3d,
                COALESCE(SUM(CASE WHEN lt.type IN ${WAGER_TYPES_SQL}  AND lt.created_at >= NOW() - INTERVAL '7 days'  THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS wagers_7d,
                COALESCE(SUM(CASE WHEN lt.type IN ${WAGER_TYPES_SQL}  AND lt.created_at >= NOW() - INTERVAL '14 days' THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS wagers_14d,
                COALESCE(SUM(CASE WHEN lt.type IN ${WAGER_TYPES_SQL}  AND lt.created_at >= NOW() - INTERVAL '30 days' THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS wagers_30d,
                -- Payouts per window — same set of types the dashboard
                -- subtracts when computing GGR (see _wager-payout-types.ts).
                COALESCE(SUM(CASE WHEN lt.type IN ${PAYOUT_TYPES_SQL} AND lt.created_at >= NOW() - INTERVAL '1 day'   THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS payouts_1d,
                COALESCE(SUM(CASE WHEN lt.type IN ${PAYOUT_TYPES_SQL} AND lt.created_at >= NOW() - INTERVAL '3 days'  THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS payouts_3d,
                COALESCE(SUM(CASE WHEN lt.type IN ${PAYOUT_TYPES_SQL} AND lt.created_at >= NOW() - INTERVAL '7 days'  THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS payouts_7d,
                COALESCE(SUM(CASE WHEN lt.type IN ${PAYOUT_TYPES_SQL} AND lt.created_at >= NOW() - INTERVAL '14 days' THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS payouts_14d,
                COALESCE(SUM(CASE WHEN lt.type IN ${PAYOUT_TYPES_SQL} AND lt.created_at >= NOW() - INTERVAL '30 days' THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS payouts_30d,
                -- Real deposits per window — lt.type='deposit', not
                -- the FTD-only acu.deposit_amount_usd. Counts every
                -- cash-in by referred users, which is what the admin
                -- expects.
                COALESCE(SUM(CASE WHEN lt.type = 'deposit'           AND lt.created_at >= NOW() - INTERVAL '1 day'   THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS deposits_1d,
                COALESCE(SUM(CASE WHEN lt.type = 'deposit'           AND lt.created_at >= NOW() - INTERVAL '3 days'  THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS deposits_3d,
                COALESCE(SUM(CASE WHEN lt.type = 'deposit'           AND lt.created_at >= NOW() - INTERVAL '7 days'  THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS deposits_7d,
                COALESCE(SUM(CASE WHEN lt.type = 'deposit'           AND lt.created_at >= NOW() - INTERVAL '14 days' THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS deposits_14d,
                COALESCE(SUM(CASE WHEN lt.type = 'deposit'           AND lt.created_at >= NOW() - INTERVAL '30 days' THEN ABS(lt.amount::numeric) ELSE 0 END), 0)::text AS deposits_30d
           FROM ledger_transactions lt
           JOIN creator_referrals cr ON cr.user_id = lt.user_id
           JOIN "user" ru            ON ru.id      = lt.user_id
          WHERE lt.status = 'completed'
            AND ru.role NOT IN ('admin', 'support')
          GROUP BY cr.creator_user_id`,
        userIds,
      ),
    ]);

  const codeById = new Map(codeRows.map((r) => [r.user_id, r.code]));
  const wagerById = new Map(
    affiliateAccounts.map((a) => [
      a.user_id,
      toNumber(a.total_wager_volume_usd),
    ]),
  );
  const signupsById = new Map(
    signupRows.map((r) => [r.user_id, Number(r.signups)]),
  );
  const ftdsById = new Map(ftdRows.map((r) => [r.user_id, Number(r.ftds)]));

  // Project the wide momentum row (one row per creator with all 5
  // periods × 3 metrics) into the nested per-period shape the UI
  // expects. PnL = wagers − payouts in house POV.
  const pnlByCreatorId = new Map<string, CreatorCodeAndWager["pnlByPeriod"]>();
  for (const r of momentumRows) {
    const project = (
      w: string,
      p: string,
      d: string,
    ): CreatorPnlByPeriod => {
      const wagers = toNumber(w);
      const payouts = toNumber(p);
      return {
        wagers,
        payouts,
        pnl: wagers - payouts,
        deposits: toNumber(d),
      };
    };
    pnlByCreatorId.set(r.creator_user_id, {
      "1d": project(r.wagers_1d, r.payouts_1d, r.deposits_1d),
      "3d": project(r.wagers_3d, r.payouts_3d, r.deposits_3d),
      "7d": project(r.wagers_7d, r.payouts_7d, r.deposits_7d),
      "14d": project(r.wagers_14d, r.payouts_14d, r.deposits_14d),
      "30d": project(r.wagers_30d, r.payouts_30d, r.deposits_30d),
    });
  }

  for (const id of userIds) {
    const pnl = pnlByCreatorId.get(id) ?? EMPTY_PNL;
    result.set(id, {
      code: codeById.get(id) ?? null,
      wagerVolumeUsd: wagerById.get(id) ?? 0,
      signups: signupsById.get(id) ?? 0,
      ftds: ftdsById.get(id) ?? 0,
      // 3d wagers + deposits surface on the existing momentum line —
      // pulled from the same per-period record so the row + the PnL
      // strip can never disagree.
      deposits3dUsd: pnl["3d"].deposits,
      wagers3dUsd: pnl["3d"].wagers,
      pnlByPeriod: pnl,
    });
  }
  return result;
}
