import "server-only";

import { getDb } from "@/lib/db";
import { toNumber } from "@/lib/utils/decimal";

export type CreatorCodeAndWager = {
  /** user.affiliate_code — the referral code this creator owns. */
  code: string | null;
  /**
   * affiliate_accounts.total_wager_volume_usd — total wager volume
   * generated by users this creator referred. Same metric the
   * /creators/[id] detail page surfaces as "Wager Volume". This is
   * NOT the creator's personal wagering (that would be
   * balances.total_wagered) — admins evaluating creators care about
   * the volume their CODE drove, not how much they personally bet.
   */
  wagerVolumeUsd: number;
};

/**
 * Fetch (code, wagerVolumeUsd) for a list of creator user_ids.
 * Keyed on user_id; missing users get a zeroed/null record so
 * callers can `.get(id) ?? EMPTY` without guards.
 *
 * The /creators page sources its list from the backend API, but
 * `user.affiliate_code` and `affiliate_accounts.total_wager_volume_usd`
 * live on the main DB and the backend list endpoint doesn't surface
 * them. Doing this enrichment here avoids touching the backend
 * contract.
 */
export async function getCodeAndWagerByUser(
  userIds: string[],
): Promise<Map<string, CreatorCodeAndWager>> {
  const result = new Map<string, CreatorCodeAndWager>();
  if (userIds.length === 0) return result;

  const db = await getDb();
  const [users, affiliateAccounts] = await Promise.all([
    db.user.findMany({
      where: { id: { in: userIds } },
      select: { id: true, affiliate_code: true },
    }),
    db.affiliate_accounts.findMany({
      where: { user_id: { in: userIds } },
      select: { user_id: true, total_wager_volume_usd: true },
    }),
  ]);

  const codeById = new Map(users.map((u) => [u.id, u.affiliate_code]));
  const wagerById = new Map(
    affiliateAccounts.map((a) => [
      a.user_id,
      toNumber(a.total_wager_volume_usd),
    ]),
  );

  for (const id of userIds) {
    result.set(id, {
      code: codeById.get(id) ?? null,
      wagerVolumeUsd: wagerById.get(id) ?? 0,
    });
  }
  return result;
}
